-- ═══════════════════════════════════════════════════════
-- Level Up Interviews — Supabase Schema
-- Run this in Supabase SQL Editor (Dashboard > SQL)
-- ═══════════════════════════════════════════════════════
-- Migration notes:
--   2026-06-21: added service_usage table + 'team' tier to profiles CHECK constraint

-- 1. Profiles (extends auth.users)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  name text not null default '',
  email text not null default '',
  target_role text default '',
  target_company text default '',
  industry text default '',
  interview_date text default '',
  experience_level text default '',
  learning_style text default 'direct',
  resume_file_name text default '',
  resume_text text default '',
  practice_timestamps jsonb default '[]'::jsonb,
  avatar_url text default '',
  subscription_tier text default 'free' check (subscription_tier in ('free', 'starter', 'pro', 'team')), -- 'team' tier: B2B/college cohort plan
  subscription_start timestamptz,
  subscription_end timestamptz,
  cancel_at_period_end boolean default false,
  subscription_paused boolean default false,
  razorpay_payment_id text,
  razorpay_subscription_id text,
  has_completed_onboarding boolean default false,
  referral_code text unique,
  referred_by text,
  preferred_session_length integer,
  interview_types jsonb default '[]'::jsonb,
  resume_data jsonb,
  -- Pointer to the resume_versions row that produced resume_data. Set
  -- right after analyze-resume returns so a tab close mid-flight or a
  -- new device on next login can resolve the canonical version. Soft
  -- FK (no foreign key constraint) so a deleted version doesn't cascade
  -- to the profile; readers should tolerate dangling pointers.
  resume_version_id uuid,
  created_at timestamptz default now()
);

-- Backfill column on existing deployments. Idempotent — safe to re-run.
alter table profiles add column if not exists resume_version_id uuid;

-- 2. Interview sessions
create table if not exists sessions (
  id text primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  date timestamptz default now(),
  type text not null,
  difficulty text not null,
  focus text default '',
  duration integer default 0,
  score integer default 0,
  questions integer default 0,
  transcript jsonb default '[]'::jsonb,
  ai_feedback text default '',
  skill_scores jsonb,
  -- Results report (generated by /api/evaluate-session, cached for re-open)
  report_json jsonb,
  report_version text default 'mvp-1',
  report_generated_at timestamptz,
  created_at timestamptz default now()
);
-- Ensure additive columns exist on upgrades (safe, idempotent)
alter table sessions add column if not exists report_json jsonb;
alter table sessions add column if not exists report_version text default 'mvp-1';
alter table sessions add column if not exists report_generated_at timestamptz;
create index if not exists idx_sessions_report_generated on sessions(report_generated_at);

-- Resume v2 binding — every session captures the exact resume_version
-- used at session start so question generation, scoring, and feedback
-- reference an immutable snapshot. NULL on legacy rows; new rows always
-- populated. Set to NULL on cascade rather than blocking so deleting an
-- old resume doesn't trash session history.
alter table sessions add column if not exists resume_version_id uuid;
create index if not exists idx_sessions_resume_version on sessions(resume_version_id);

-- 3. Calendar events
create table if not exists calendar_events (
  id text primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  company text default '',
  date text not null,
  time text default '',
  type text default 'interview',
  notes text default '',
  created_at timestamptz default now()
);

-- Calendar rebuild (PRI-35): timezone-correct, prep-runway-aware model.
-- Additive + idempotent so it applies cleanly to the deployed table that
-- still has the naive date/time text columns. `date`/`time` are retained
-- for backward compatibility and one-way display; `start_utc`/`end_utc`
-- are the authoritative instants going forward.
alter table calendar_events add column if not exists start_utc timestamptz;
alter table calendar_events add column if not exists end_utc timestamptz;
-- IANA zone the event was authored in (candidate-local). Default reflects
-- the core Indian-candidate audience.
alter table calendar_events add column if not exists timezone text default 'Asia/Kolkata';
alter table calendar_events add column if not exists duration_minutes int default 60;
-- target role/position for the interview; feeds the mock deep-link prefill and
-- round-aware prep. Additive so it applies cleanly to the deployed table.
alter table calendar_events add column if not exists role text default '';
alter table calendar_events add column if not exists location text default '';
-- upcoming | completed | cancelled
alter table calendar_events add column if not exists status text default 'upcoming';
-- real | prep-session  (prep-session rows are the auto-scheduled mock runway)
alter table calendar_events add column if not exists kind text default 'real';
-- self-reference: a prep-session points at the real interview it prepares for
alter table calendar_events add column if not exists parent_interview_id text;
-- manual | nl | google | prep-runway
alter table calendar_events add column if not exists source text default 'manual';
alter table calendar_events add column if not exists google_event_id text;
-- array of { channel: 'email' | 'push', minutesBefore: int }
alter table calendar_events add column if not exists reminders jsonb default '[]'::jsonb;
alter table calendar_events add column if not exists updated_at timestamptz default now();

-- Idempotent send-log for calendar reminders (PRI-35). One row per
-- (event, channel, lead-time) that has actually been delivered, so the daily
-- reminder cron never double-sends. The unique constraint is the dedup key;
-- the cron upserts on conflict do-nothing. Writes come from the service role
-- (cron); RLS only governs the owner's read access.
create table if not exists calendar_reminder_log (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  event_id text references calendar_events(id) on delete cascade not null,
  channel text not null,
  minutes_before int not null,
  sent_at timestamptz not null default now(),
  unique (event_id, channel, minutes_before)
);
create index if not exists idx_reminder_log_event on calendar_reminder_log(event_id);
create index if not exists idx_reminder_log_user on calendar_reminder_log(user_id);
alter table calendar_reminder_log enable row level security;
drop policy if exists "Users read own reminder log" on calendar_reminder_log;
create policy "Users read own reminder log" on calendar_reminder_log
  for select using ((auth.uid())::text = user_id::text);

-- Google Calendar two-way sync state (PRI-35). One row per connected user.
-- Holds the long-lived refresh token (the access token is short-lived and
-- refreshed on demand), the incremental nextSyncToken, and the push-channel
-- (watch) identifiers so the webhook can map an inbound notification back to a
-- user and the poll cron can renew expiring channels. Service-role only for
-- writes; the owner may read their own connection status. The refresh_token is
-- a secret: never expose it through a client-readable view or column select.
create table if not exists google_calendar_sync (
  user_id uuid primary key references profiles(id) on delete cascade,
  refresh_token text not null,
  access_token text,
  token_expiry timestamptz,
  sync_token text,
  calendar_id text not null default 'primary',
  channel_id text,
  resource_id text,
  channel_expiry timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_gcal_sync_channel on google_calendar_sync(channel_id, resource_id);
alter table google_calendar_sync enable row level security;
-- Owner can see whether they're connected and when it expires, but NOT the
-- token columns in practice (clients should select only status fields). The
-- policy scopes by ownership; secret hygiene is enforced by never selecting
-- refresh_token/access_token from the client.
drop policy if exists "Users read own google sync" on google_calendar_sync;
create policy "Users read own google sync" on google_calendar_sync
  for select using ((auth.uid())::text = user_id::text);

-- 4. Feedback
create table if not exists feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  session_id text references sessions(id) on delete cascade not null,
  rating text check (rating in ('helpful', 'too_harsh', 'too_generous', 'inaccurate')) not null,
  comment text default '',
  session_score integer default 0,
  session_type text default '',
  created_at timestamptz default now()
);

-- 4c. Coming-soon / launch waitlist
-- Public anon-insertable list of emails captured before launch via the
-- ComingSoon page. Email is the primary key so the upsert {onConflict:'email'}
-- pattern in src/ComingSoon.tsx works without creating duplicates.
-- Anonymous SELECT is intentionally NOT granted — waitlist emails are
-- private; only the service role reads them (for the launch broadcast).
create table if not exists waitlist (
  email text primary key,
  created_at timestamptz default now(),
  source text default 'coming_soon',
  -- Optional referral / UTM fields for future attribution. Nullable so
  -- existing form callers (which only send email + created_at) still work.
  referrer text default '',
  utm_source text default '',
  utm_medium text default '',
  utm_campaign text default ''
);
create index if not exists idx_waitlist_created on waitlist(created_at desc);

-- 4b. Per-question feedback (active-learning loop)
-- Captures the user's signal on EACH generated question so we can mine
-- under-performing patterns and feed corrections back into the curated
-- bank. Distinct from `feedback` (above) which is whole-session sentiment.
-- thumbs: 'up' = realistic / good question; 'down' = off-base / generic;
--         'real' = candidate marks "this matched my real interview"
create table if not exists question_feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  session_id text references sessions(id) on delete cascade not null,
  question_index integer not null,           -- ordinal in the session script
  question_text text not null,                -- exact text shown to candidate
  thumbs text check (thumbs in ('up', 'down', 'real')) not null,
  -- denormalised setup so we can aggregate without joining sessions
  company text default '',
  role text default '',
  focus text default '',
  comment text default '',
  created_at timestamptz default now()
);
create index if not exists idx_question_feedback_user on question_feedback(user_id, created_at desc);
create index if not exists idx_question_feedback_company_focus on question_feedback(company, focus, created_at desc);
-- Upsert key: latest thumbs per (user, session, question) wins
create unique index if not exists ux_question_feedback_per_question on question_feedback(user_id, session_id, question_index);

-- Credibility-callout dispute log. Every row is a candidate saying "the
-- analyzer's BGV-risk flag is wrong" for a specific (session, flag) pair.
-- Drives false-positive auditing for the Wave-9 credibility callout:
-- a per-flag dispute rate that climbs above ~3% means the detection
-- regex is overfiring and the analyzer needs a tightening pass. One row
-- per (user, session, flag) — last write wins on the upsert.
create table if not exists credibility_disputes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  session_id text references sessions(id) on delete cascade not null,
  flag text not null,                 -- e.g. 'cgpa_mismatch_with_resume'
  analyzer_version text default '',   -- pinned at dispute time for forensics
  reason text default '',             -- optional user-typed context (<=500ch)
  created_at timestamptz default now()
);
create index if not exists idx_credibility_disputes_flag on credibility_disputes(flag, created_at desc);
create unique index if not exists ux_credibility_disputes_per_flag on credibility_disputes(user_id, session_id, flag);

-- 5. Payments
create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  razorpay_payment_id text unique not null,
  razorpay_order_id text default '',
  plan text not null,
  tier text not null,
  amount integer not null,
  currency text default 'INR',
  status text default 'completed',
  subscription_start timestamptz,
  subscription_end timestamptz,
  receipt_url text default '',
  created_at timestamptz default now()
);
alter table payments add column if not exists receipt_url text default '';

-- 5b. Payment dedup
-- Atomic guard against duplicate verify-payment activations. A single
-- UNIQUE row per Razorpay payment id; the verify handler INSERTs with
-- on-conflict-do-nothing and treats the conflict as "already processed".
create table if not exists payment_dedup (
  razorpay_payment_id text primary key,
  user_id uuid references profiles(id) on delete cascade,
  created_at timestamptz default now()
);
-- Service-role-only: written exclusively by verify-payment / webhook via the
-- service key (which bypasses RLS). Enabling RLS with NO authenticated/anon
-- policy denies all client access — defense-in-depth so payment ids never leak
-- through PostgREST even if an anon/auth key is misused.
alter table payment_dedup enable row level security;

-- ═══════════════════════════════════════════════════════
-- Performance Indexes
-- ═══════════════════════════════════════════════════════

create index if not exists idx_profiles_tier_end on profiles(subscription_tier, subscription_end);
create index if not exists idx_sessions_user_created on sessions(user_id, created_at);
create index if not exists idx_sessions_user_date on sessions(user_id, date);
create index if not exists idx_payments_razorpay_id on payments(razorpay_payment_id);
create index if not exists idx_calendar_events_user on calendar_events(user_id, date);
create index if not exists idx_calendar_events_user_start on calendar_events(user_id, start_utc);
create index if not exists idx_calendar_events_parent on calendar_events(parent_interview_id);
-- One linked Google event per user; ignores rows that aren't Google-sourced.
create unique index if not exists idx_calendar_events_google
  on calendar_events(user_id, google_event_id)
  where google_event_id is not null;
create index if not exists idx_feedback_session on feedback(session_id);
create index if not exists idx_feedback_user on feedback(user_id, created_at);

-- ═══════════════════════════════════════════════════════
-- 6. Referral codes
-- ═══════════════════════════════════════════════════════

create table if not exists referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid references profiles(id) on delete cascade not null,
  -- NOTE: referral_code is the REFERRER's code and repeats across every
  -- person they refer, so it must NOT be unique (a unique constraint here
  -- silently capped each referrer at a single referral). One-referral-per-
  -- referred-user is enforced instead by uniq_referrals_referred below.
  referral_code text not null,
  referred_email text,
  referred_id uuid references profiles(id) on delete set null,
  status text default 'pending' check (status in ('pending', 'redeemed', 'rewarded')),
  reward_granted boolean default false,
  -- Compare-and-swap gate for the double-sided reward. NULL = not yet paid
  -- out; a single atomic PATCH flips it null → now() so a double-fire (retry,
  -- concurrent SIGNED_IN) can never double-grant credits. See
  -- _referral-reward-helpers.ts claimReferralReward().
  reward_granted_at timestamptz,
  created_at timestamptz default now()
);

create index if not exists idx_referrals_code on referrals(referral_code);
create index if not exists idx_referrals_referrer on referrals(referrer_id);
-- A given user can be referred at most once. Partial (referred_id is null
-- only for legacy email-invite rows that were never redeemed).
create unique index if not exists uniq_referrals_referred
  on referrals(referred_id) where referred_id is not null;

-- ── Idempotent migration for already-deployed databases ──
-- `create table if not exists` above is a no-op on an existing table, so the
-- structural fixes (drop the one-referral-per-referrer unique, add the CAS
-- column) are applied explicitly here. Safe to re-run.
alter table referrals drop constraint if exists referrals_referral_code_key;
alter table referrals add column if not exists reward_granted_at timestamptz;

-- 7. Promo / coupon codes
create table if not exists promo_codes (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  discount_percent integer default 0 check (discount_percent between 0 and 100),
  discount_amount integer default 0,
  valid_from timestamptz default now(),
  valid_until timestamptz,
  max_uses integer default 0,
  current_uses integer default 0,
  applicable_plans text[] default '{}',
  created_at timestamptz default now()
);

create index if not exists idx_promo_codes_code on promo_codes(code);

-- 8. LLM usage tracking
create table if not exists llm_usage (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete set null,
  endpoint text not null,          -- 'generate' | 'follow-up' | 'evaluate' | 'analyze-resume'
  model text not null,             -- 'llama-3.3-70b-versatile' | 'gemini-2.0-flash' etc.
  is_fallback boolean default false,
  prompt_tokens integer default 0,
  completion_tokens integer default 0,
  total_tokens integer default 0,
  latency_ms integer default 0,
  status text default 'success' check (status in ('success', 'error', 'timeout')),
  error_message text,
  created_at timestamptz default now()
);

create index if not exists idx_llm_usage_user_created on llm_usage(user_id, created_at);
create index if not exists idx_llm_usage_endpoint on llm_usage(endpoint, created_at);
create index if not exists idx_llm_usage_created on llm_usage(created_at);

-- 9. Role competencies + company guidance
--
-- Mirrors the ROLE_COMPETENCIES + COMPANY_GUIDANCE maps currently hardcoded
-- in server-handlers/generate-questions.ts. The in-code constants are still
-- the source of truth; generate-questions.ts falls back to them when the DB
-- row is absent. Purpose: allow non-deploy updates, versioning, and eventual
-- A/B testing of question prompts per role/company.
--
-- Seeding is a separate migration step — creating the tables here is safe on
-- an empty DB because the fallback path keeps behaviour unchanged.
create table if not exists role_competencies (
  role_slug text primary key,
  body text not null,
  version integer default 1,
  updated_at timestamptz default now()
);
create table if not exists company_guidance (
  company_slug text primary key,
  body text not null,
  version integer default 1,
  updated_at timestamptz default now()
);
alter table role_competencies enable row level security;
alter table company_guidance enable row level security;
drop policy if exists "Anyone can read role competencies" on role_competencies;
create policy "Anyone can read role competencies" on role_competencies for select using (true);
drop policy if exists "Anyone can read company guidance" on company_guidance;
create policy "Anyone can read company guidance" on company_guidance for select using (true);
-- Writes only via service role (bypasses RLS). No INSERT/UPDATE/DELETE policy
-- for authenticated users — this data is admin-controlled.

-- 10. Story Notebook — removed. The feature is gone; drop the table if it
-- still exists from a previous deploy.
drop table if exists story_notebook;

-- 10. Report shares — tokenized public links to a session report
-- Used by candidates to share their results with recruiters / mentors.
-- The token is the public identifier (URL-safe random); session_id stays
-- private. expires_at gates anonymous access; revoked_at lets the owner
-- kill the link on demand. view_count tracks how many times the link
-- was opened so the owner sees engagement.
create table if not exists report_shares (
  token text primary key,
  session_id text references sessions(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  view_count integer default 0,
  last_viewed_at timestamptz,
  -- Optional candidate-controlled visibility flags. Defaults are conservative:
  -- transcripts and per-question content are HIDDEN unless the user opts in.
  include_transcript boolean default false,
  include_per_question boolean default false,
  created_at timestamptz default now()
);

create index if not exists idx_report_shares_session on report_shares(session_id);
create index if not exists idx_report_shares_user on report_shares(user_id, created_at desc);
create index if not exists idx_report_shares_expires on report_shares(expires_at) where revoked_at is null;

alter table report_shares enable row level security;
-- Owner can manage their own share rows. Public reads happen via service
-- role from /api/get-shared-report, NOT via RLS.
drop policy if exists "Users manage own shares" on report_shares;
create policy "Users manage own shares" on report_shares
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 11. Outcome tracking — voluntary self-report so we can build real
-- "X candidates landed Y offers" case studies (currently the biggest
-- investor-pitch gap). Users opt in via a banner on the dashboard
-- after they've completed ≥3 sessions.
create table if not exists user_outcomes (
  user_id uuid references profiles(id) on delete cascade primary key,
  applied boolean,
  interviewed boolean,
  offer boolean,
  accepted boolean,
  company text,
  role_landed text,
  testimonial text,
  may_share_publicly boolean default false,
  reported_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_user_outcomes_offer on user_outcomes(offer) where offer = true;
create index if not exists idx_user_outcomes_share on user_outcomes(may_share_publicly) where may_share_publicly = true;

alter table user_outcomes enable row level security;
drop policy if exists "Users manage own outcomes" on user_outcomes;
create policy "Users manage own outcomes" on user_outcomes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════
-- 11. Resume management — multi-resume + version history
--
-- Replaces the single-resume-per-user pattern (profile.resume_data jsonb).
-- The legacy column stays during a sunset window — handlers prefer the
-- new tables but fall back to profile.resume_data when missing.
--
--   resumes              — one logical resume per (user, domain).
--   resume_versions      — immutable history; one row per upload.
--   sessions.resume_version_id (added above) — pin to the version that
--                          ran the interview so scores are reproducible.
--
-- Hash-based AI dedup: text_hash is SHA256 of the normalized resume
-- text. analyze-resume.ts checks for an existing version with the same
-- hash before calling the LLM — same content → cached parse.
-- ═══════════════════════════════════════════════════════

create table if not exists resumes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  domain text not null default 'general',         -- 'sde' | 'pm' | 'sales' | 'design' | 'general' | custom
  title text default '',                           -- "PM Resume — Product Companies"
  is_archived boolean default false,
  active_version_id uuid,                          -- soft FK to resume_versions(id); set after the version row exists
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_resumes_user_archived on resumes(user_id, is_archived);
create index if not exists idx_resumes_user_domain on resumes(user_id, domain);

create table if not exists resume_versions (
  id uuid primary key default gen_random_uuid(),
  resume_id uuid references resumes(id) on delete cascade not null,
  version_number integer not null,                 -- 1, 2, 3...
  file_hash text,                                  -- SHA256 of original file bytes (null for text-only uploads)
  text_hash text not null,                         -- SHA256 of normalized resume_text
  file_path text,                                  -- Supabase Storage path (null until file upload added)
  file_name text,
  resume_text text,                                -- normalized text, capped at 50KB upstream
  parsed_data jsonb,                               -- AI ResumeProfile or fallback ParsedResume
  parse_source text default 'ai',                  -- 'ai' | 'fallback' | 'cached'
  is_latest boolean default true,
  created_at timestamptz default now()
);
create unique index if not exists idx_resume_versions_unique on resume_versions(resume_id, version_number);
create index if not exists idx_resume_versions_text_hash on resume_versions(text_hash);
create index if not exists idx_resume_versions_file_hash on resume_versions(file_hash);
create index if not exists idx_resume_versions_resume on resume_versions(resume_id, is_latest);

alter table resumes enable row level security;
alter table resume_versions enable row level security;

-- IMPORTANT: every policy compares (auth.uid())::text = column::text.
-- Reason: auth.uid() returns either text or uuid depending on the
-- Supabase Postgres version. Older projects ship the text variant;
-- newer ones ship uuid. Casting both sides to text avoids the
-- "operator does not exist: uuid = text" parse error on either flavor.
-- Performance impact is negligible (still indexed via the cast).

drop policy if exists "Users view own resumes" on resumes;
create policy "Users view own resumes" on resumes
  for select using ((auth.uid())::text = user_id::text);
drop policy if exists "Users insert own resumes" on resumes;
create policy "Users insert own resumes" on resumes
  for insert with check ((auth.uid())::text = user_id::text);
drop policy if exists "Users update own resumes" on resumes;
create policy "Users update own resumes" on resumes
  for update using ((auth.uid())::text = user_id::text) with check ((auth.uid())::text = user_id::text);
drop policy if exists "Users delete own resumes" on resumes;
create policy "Users delete own resumes" on resumes
  for delete using ((auth.uid())::text = user_id::text);

-- resume_versions inherits user-ownership via resume_id join. We don't
-- duplicate user_id on the version row to avoid drift; reads/writes go
-- through the resume parent.
drop policy if exists "Users view own versions" on resume_versions;
create policy "Users view own versions" on resume_versions
  for select using (
    exists (select 1 from resumes r where r.id = resume_versions.resume_id and r.user_id::text = (auth.uid())::text)
  );
drop policy if exists "Users insert own versions" on resume_versions;
create policy "Users insert own versions" on resume_versions
  for insert with check (
    exists (select 1 from resumes r where r.id = resume_versions.resume_id and r.user_id::text = (auth.uid())::text)
  );
-- No UPDATE/DELETE policy for users — versions are immutable. Service
-- role can flip is_latest when a newer version is added.

-- ═══════════════════════════════════════════════════════
-- Used verification tokens
-- ═══════════════════════════════════════════════════════
-- One-shot consumption ledger for email-verification tokens. The
-- HMAC validator (verify-email.ts) only proves a token is well-formed
-- and unexpired; it doesn't prove it hasn't been used. Without this
-- table, anyone who intercepted a verification link AFTER it was
-- clicked could re-confirm the account from a fresh device, or — if
-- the EMAIL_VERIFICATION_SECRET ever leaks — forge tokens for any
-- email and have them all accepted indefinitely until the 48h window
-- expires.
--
-- We store the SHA-256 of the token (not the token itself) so a leak
-- of this table doesn't double as a leak of unused tokens. Service
-- role only — users have no business reading this directly.
create table if not exists used_verification_tokens (
  -- Primary key is the token-hash, not an autogen uuid: the natural
  -- uniqueness IS the dedup key. Insert-or-conflict is the consumption
  -- check. 64-char hex (SHA-256).
  token_hash text primary key,
  -- Email the token was issued to. Stored for forensic lookups only —
  -- attacks would tamper with the email param too, so we don't trust
  -- this for validation, just for auditability.
  email text not null,
  used_at timestamptz not null default now()
);
-- Auto-purge entries older than 7 days. Tokens themselves are only
-- valid for 48h; keeping a few extra days of replay-defense ledger is
-- belt-and-suspenders for late-clicked links.
create index if not exists idx_used_verification_tokens_used_at
  on used_verification_tokens(used_at);

-- Service-role only; no user-facing policies.
alter table used_verification_tokens enable row level security;

-- ═══════════════════════════════════════════════════════
-- Row Level Security (RLS)
-- Users can only access their own data
-- ═══════════════════════════════════════════════════════

-- Weekly-summary cron uses this to rate-limit emails per user.
alter table profiles add column if not exists last_summary_email_at timestamptz;

-- Bonus-session economy retired. Zero out any outstanding balances before
-- dropping the columns so existing rows don't carry orphaned values into
-- any downstream snapshot/backup tooling that still references them.
update profiles set session_credits = 0 where session_credits is not null and session_credits <> 0;
alter table profiles drop column if exists session_credits;
alter table profiles drop column if exists last_streak_reward_day;

-- ═══════════════════════════════════════════════════════
-- Session credits (single-session "₹9 per session" purchases)
-- ═══════════════════════════════════════════════════════
-- A credit lets a free-tier user run one mock interview beyond
-- FREE_SESSION_LIMIT. Bought via the "single" Razorpay plan (1–10 per order).
--
-- SECURITY — why this is its own table, not a profiles column:
-- the profiles UPDATE policy is row-scoped (auth.uid() = id) with NO column
-- restriction, so an authenticated user can PATCH their own profile row. A
-- balance column there would be self-grantable (free unlimited sessions). Here,
-- the owner gets SELECT only; there is deliberately NO insert/update/delete
-- policy for authenticated/anon, so ONLY the service role (which bypasses RLS)
-- can mint or spend credits — from server-handlers/_session-credits.ts.
create table if not exists session_credits (
  user_id    uuid primary key references profiles(id) on delete cascade,
  balance    integer not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);
alter table session_credits enable row level security;

-- Owner may read their own balance (for the dashboard credit pill). No write
-- policy is intentional — writes happen only via the service-role key.
drop policy if exists "Users read own session credits" on session_credits;
create policy "Users read own session credits" on session_credits
  for select using ((auth.uid())::text = user_id::text);

-- Atomic single-credit spend (audit N-4). The previous helper did a non-atomic
-- read-then-PATCH, so two near-simultaneous session starts could both pass the
-- balance>0 check and spend a single credit twice. This function decrements in
-- one UPDATE statement guarded by `balance > 0`; Postgres row-locking serializes
-- concurrent calls, so the second sees the already-decremented balance and the
-- WHERE no longer matches. Returns true iff a credit was actually consumed.
-- Execute is restricted to the service role: a user must not be able to drain
-- another user's credits by calling the RPC with a different user_id.
create or replace function consume_session_credit(p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  update session_credits
     set balance = balance - 1,
         updated_at = now()
   where user_id = p_user_id
     and balance > 0;
  get diagnostics affected = row_count;
  return affected > 0;
end;
$$;

revoke all on function consume_session_credit(uuid) from public, anon, authenticated;
grant execute on function consume_session_credit(uuid) to service_role;

-- ── Atomic promo code consumption ─────────────────────────────────────────────
-- Increments current_uses only when uses < max_uses. Returns the code row id
-- on success, null when the code doesn't exist or is already exhausted.
-- Called by verify-payment.ts to eliminate the non-atomic read-then-patch race.
create or replace function consume_promo_code(p_code text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  update promo_codes
  set current_uses = current_uses + 1
  where code = p_code
    and (max_uses is null or current_uses < max_uses)
  returning id into v_id;
  return v_id;
end;
$$;

-- Restrict execution to service role only (anon/authenticated cannot call this)
revoke all on function consume_promo_code(text) from public;
revoke all on function consume_promo_code(text) from anon;
revoke all on function consume_promo_code(text) from authenticated;
grant execute on function consume_promo_code(text) to service_role;

-- Re-engagement cron uses this to rate-limit emails per user (see re-engage-users.ts).
alter table profiles add column if not exists re_engage_sent timestamptz;

-- Idempotency tracking for session-start counting. /api/record-session-start
-- appends the sessionId here when the user enters /interview, so save-session
-- knows not to double-bump practice_timestamps on completion. Last 50 ids
-- retained — older ones get pruned on each write.
alter table profiles add column if not exists started_session_ids jsonb default '[]'::jsonb;

-- Soft-delete marker. delete-account.ts (PATCH path) sets this on
-- user-requested account deletion; cleanup-deleted-accounts.ts
-- permanently removes profiles where deleted_at < now() - 7 days.
-- Restore path (login within the window) clears the field.
alter table profiles add column if not exists deleted_at timestamptz;
create index if not exists profiles_deleted_at_idx on profiles (deleted_at) where deleted_at is not null;

-- Public-profile opt-in. The /api/public-profile endpoint only serves a
-- profile when this is explicitly true — private by default so a new user
-- is never publicly listed without opting in. Existing rows default to
-- false on add, matching the private-by-default contract.
alter table profiles add column if not exists is_profile_public boolean not null default false;

-- Monotonic lifetime session-start counter (audit P0-2). The free-tier limit
-- was derived by counting rows in `sessions`, but users may delete their own
-- sessions (RLS allows it), so deleting rows reset the free allotment back to
-- zero — effectively unlimited free sessions. This column is a high-water mark
-- that only ever increments (via the trigger below); deletes never touch it,
-- so checkSessionLimit can gate the free cap on it instead of the live count.
alter table profiles add column if not exists sessions_started_lifetime integer not null default 0;

-- Backfill existing users to their current session-row count so the high-water
-- mark starts at the right place (greatest() keeps it monotonic if re-run).
update profiles p set sessions_started_lifetime = greatest(
  coalesce(p.sessions_started_lifetime, 0),
  (select count(*) from sessions s where s.user_id = p.id)
);

-- Increment the counter on every session insert. SECURITY DEFINER so it can
-- write profiles regardless of the caller's RLS context; the billing guard
-- trigger above does not touch this column, so the increment survives. Deletes
-- have no corresponding trigger, which is the whole point — the count is
-- delete-proof. Idempotent: drops and recreates cleanly on re-run.
create or replace function bump_sessions_started_lifetime()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update profiles
    set sessions_started_lifetime = sessions_started_lifetime + 1
    where id = new.user_id;
  return new;
end;
$$;

drop trigger if exists trg_bump_sessions_lifetime on sessions;
create trigger trg_bump_sessions_lifetime
  after insert on sessions
  for each row execute function bump_sessions_started_lifetime();

-- ═══════════════════════════════════════════════════════
-- Support messages (Help & Support widget "Send Feedback")
-- ═══════════════════════════════════════════════════════
-- Free-text feedback/issue reports from the floating "?" widget. Distinct
-- from `feedback` (per-session rating) and `question_feedback` (per-question
-- thumbs). Written ONLY by the service role via /api/support-feedback after an
-- authenticated request — there is deliberately no insert/update/delete policy
-- for end users, so a client can't forge or tamper with the queue. The author
-- may read their own submissions; you (the operator) read the whole queue in
-- the Supabase dashboard, ordered by created_at. user_id is set null (not
-- cascade-deleted) so a support thread survives the author deleting their
-- account.
create table if not exists support_messages (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid references profiles(id) on delete set null,
  email      text,
  message    text not null,
  page       text,
  user_agent text,
  status     text not null default 'new' check (status in ('new', 'seen', 'resolved')),
  created_at timestamptz not null default now()
);
alter table support_messages enable row level security;
create index if not exists idx_support_messages_created on support_messages (created_at desc);

drop policy if exists "Users read own support messages" on support_messages;
create policy "Users read own support messages" on support_messages
  for select using ((auth.uid())::text = user_id::text);

alter table profiles enable row level security;
alter table sessions enable row level security;
alter table calendar_events enable row level security;
alter table feedback enable row level security;
alter table payments enable row level security;

-- Profiles: users can read/update their own profile.
-- All `create policy` statements are paired with `drop policy if exists`
-- so the entire schema file stays idempotent — re-running this file in
-- the Supabase SQL editor never errors with "policy already exists".
drop policy if exists "Users can view own profile" on profiles;
create policy "Users can view own profile" on profiles
  for select using ((auth.uid())::text = id::text);
drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile" on profiles
  for update using ((auth.uid())::text = id::text);
drop policy if exists "Users can insert own profile" on profiles;
create policy "Users can insert own profile" on profiles
  for insert with check ((auth.uid())::text = id::text);

-- SECURITY — billing-column guard (payment-bypass fix):
-- RLS on profiles is ROW-level only. The "Users can update own profile" policy
-- lets a user PATCH any column on their own row — including subscription_tier —
-- so an authenticated user could self-promote to 'pro' for free via a raw
-- PostgREST call. Postgres RLS cannot restrict columns, so we enforce it with a
-- BEFORE UPDATE trigger: any update NOT made by the service role has the
-- billing-sensitive columns silently reset to their existing values. The
-- service role (used only by verify-payment.ts / razorpay-webhook.ts after a
-- signature-verified charge) bypasses the guard and is the ONLY path that can
-- change a tier. Idempotent: re-running drops and recreates cleanly.
create or replace function guard_profile_billing_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- auth.role() is 'service_role' for service-key requests, 'authenticated'
  -- (or 'anon') for end-user requests. Only the service role may mutate billing.
  if coalesce(auth.role(), '') <> 'service_role' then
    new.subscription_tier        := old.subscription_tier;
    new.subscription_start       := old.subscription_start;
    new.subscription_end         := old.subscription_end;
    new.razorpay_payment_id      := old.razorpay_payment_id;
    new.razorpay_subscription_id := old.razorpay_subscription_id;
    new.cancel_at_period_end     := old.cancel_at_period_end;
    new.subscription_paused      := old.subscription_paused;
    -- sessions_started_lifetime is a monotonic high-water mark that gates the
    -- free-session cap (audit P0-2). RLS is row-level only, so without this a
    -- user could PATCH /rest/v1/profiles setting it back to 0 and reset their
    -- free allotment — defeating the whole counter. Enforce monotonicity for
    -- non-service-role writes: the bump_sessions_started_lifetime trigger (which
    -- runs in the user's role context) may still RAISE it by +1, but no caller
    -- may LOWER it. A user raising it only hurts themselves, so that's harmless.
    if new.sessions_started_lifetime < old.sessions_started_lifetime then
      new.sessions_started_lifetime := old.sessions_started_lifetime;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_guard_profile_billing on profiles;
create trigger trg_guard_profile_billing
  before update on profiles
  for each row execute function guard_profile_billing_columns();

-- Sessions: users can CRUD their own sessions
drop policy if exists "Users can view own sessions" on sessions;
create policy "Users can view own sessions" on sessions
  for select using ((auth.uid())::text = user_id::text);
drop policy if exists "Users can insert own sessions" on sessions;
create policy "Users can insert own sessions" on sessions
  for insert with check ((auth.uid())::text = user_id::text);
drop policy if exists "Users can delete own sessions" on sessions;
create policy "Users can delete own sessions" on sessions
  for delete using ((auth.uid())::text = user_id::text);

-- Calendar: users can CRUD their own events
drop policy if exists "Users can view own events" on calendar_events;
create policy "Users can view own events" on calendar_events
  for select using ((auth.uid())::text = user_id::text);
drop policy if exists "Users can insert own events" on calendar_events;
create policy "Users can insert own events" on calendar_events
  for insert with check ((auth.uid())::text = user_id::text);
drop policy if exists "Users can delete own events" on calendar_events;
create policy "Users can delete own events" on calendar_events
  for delete using ((auth.uid())::text = user_id::text);
drop policy if exists "Users can update own events" on calendar_events;
create policy "Users can update own events" on calendar_events
  for update using ((auth.uid())::text = user_id::text)
  with check ((auth.uid())::text = user_id::text);

-- Feedback: users can CRUD their own feedback
drop policy if exists "Users can view own feedback" on feedback;
create policy "Users can view own feedback" on feedback
  for select using ((auth.uid())::text = user_id::text);
drop policy if exists "Users can insert own feedback" on feedback;
create policy "Users can insert own feedback" on feedback
  for insert with check ((auth.uid())::text = user_id::text);
drop policy if exists "Users can update own feedback" on feedback;
create policy "Users can update own feedback" on feedback
  for update using ((auth.uid())::text = user_id::text);
drop policy if exists "Users can delete own feedback" on feedback;
create policy "Users can delete own feedback" on feedback
  for delete using ((auth.uid())::text = user_id::text);

-- Waitlist: anyone (including unauthenticated visitors on the
-- ComingSoon page) can INSERT their email. Nobody can SELECT — the
-- service role reads it for the launch broadcast. Update/delete
-- locked too; admin tooling uses the service role.
alter table waitlist enable row level security;
drop policy if exists "Anyone can insert waitlist email" on waitlist;
create policy "Anyone can insert waitlist email" on waitlist
  for insert to anon, authenticated with check (true);
drop policy if exists "Service role manages waitlist" on waitlist;
create policy "Service role manages waitlist" on waitlist
  for all to service_role using (true) with check (true);

-- Question feedback (active-learning loop): users CRUD their own only.
-- Service role aggregates across all rows for the curation pipeline.
alter table question_feedback enable row level security;
drop policy if exists "Users can view own question feedback" on question_feedback;
create policy "Users can view own question feedback" on question_feedback
  for select using ((auth.uid())::text = user_id::text);
drop policy if exists "Users can insert own question feedback" on question_feedback;
create policy "Users can insert own question feedback" on question_feedback
  for insert with check ((auth.uid())::text = user_id::text);
drop policy if exists "Users can update own question feedback" on question_feedback;
create policy "Users can update own question feedback" on question_feedback
  for update using ((auth.uid())::text = user_id::text);

-- Credibility disputes: candidate-owned. Users insert/update their own
-- rows; service role aggregates across users for false-positive auditing.
alter table credibility_disputes enable row level security;
drop policy if exists "Users can view own credibility disputes" on credibility_disputes;
create policy "Users can view own credibility disputes" on credibility_disputes
  for select using ((auth.uid())::text = user_id::text);
drop policy if exists "Users can insert own credibility disputes" on credibility_disputes;
create policy "Users can insert own credibility disputes" on credibility_disputes
  for insert with check ((auth.uid())::text = user_id::text);
drop policy if exists "Users can update own credibility disputes" on credibility_disputes;
create policy "Users can update own credibility disputes" on credibility_disputes
  for update using ((auth.uid())::text = user_id::text);

-- Payments: users can only view their own payments (insert via service role only)
drop policy if exists "Users can view own payments" on payments;
create policy "Users can view own payments" on payments
  for select using ((auth.uid())::text = user_id::text);

-- Referrals: users can view/create their own referrals
alter table referrals enable row level security;
drop policy if exists "Users can view own referrals" on referrals;
create policy "Users can view own referrals" on referrals
  for select using ((auth.uid())::text = referrer_id::text);
drop policy if exists "Users can insert own referrals" on referrals;
create policy "Users can insert own referrals" on referrals
  for insert with check ((auth.uid())::text = referrer_id::text);

-- Promo codes: anyone can read (validation is server-side)
alter table promo_codes enable row level security;
drop policy if exists "Anyone can view promo codes" on promo_codes;
create policy "Anyone can view promo codes" on promo_codes
  for select using (true);

-- LLM usage: users can view their own usage (insert via service role only)
alter table llm_usage enable row level security;
drop policy if exists "Users can view own llm usage" on llm_usage;
create policy "Users can view own llm usage" on llm_usage
  for select using ((auth.uid())::text = user_id::text);
-- Explicit INSERT policy as a safety net. The `service_role` key bypasses RLS
-- by design, but if SUPABASE_SERVICE_ROLE_KEY is ever misconfigured (e.g. set
-- to the anon key instead), writes would silently fail with a 401/403. This
-- allows service_role to insert regardless of bypass behavior.
drop policy if exists "Service role can insert llm usage" on llm_usage;
create policy "Service role can insert llm usage" on llm_usage
  for insert to service_role with check (true);

-- ═══════════════════════════════════════════════════════
-- Auto-create profile on signup
-- ═══════════════════════════════════════════════════════

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name', '')
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger: fire after signup
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ═══════════════════════════════════════════════════════
-- Session Quality Control — analyzer pipeline
-- ═══════════════════════════════════════════════════════
-- A nightly cron (analyze-sessions) re-reads each completed session
-- and writes structured findings here. Per-focus analyzers produce a
-- uniform AnalyzerResult so the dashboard and aggregation queries
-- don't care which analyzer ran.

-- Backfill columns the save-session handler writes but earlier schemas
-- didn't declare. The handler's column-stripping retry loop silently
-- dropped these on fresh DBs.
alter table sessions add column if not exists job_description text;
alter table sessions add column if not exists jd_analysis jsonb;

-- Target role + company captured at session start. Drives question
-- generation and salary-neg realism but was previously only in URL
-- params — never persisted, so the admin Quality dashboard couldn't
-- show what the candidate was practicing for.
alter table sessions add column if not exists target_role text;
alter table sessions add column if not exists target_company text;
create index if not exists idx_sessions_target_role on sessions(target_role);
create index if not exists idx_sessions_target_company on sessions(target_company);

-- Kernel-aware negotiation metrics (salary-neg sessions only). Stores
-- the structured summary computed by _negotiation-metrics.ts at session
-- end: outcome, anchorTurn, leverDiversity, lpaGained, lpaPerTurn,
-- bandTraversal, overBandViolation, totalTurns, score. NULL for any
-- non-negotiation session. Idempotent ALTER for safe rollout.
alter table sessions add column if not exists negotiation_metrics jsonb;
create index if not exists idx_sessions_negotiation_metrics_score on sessions((negotiation_metrics->>'score'));

create table if not exists session_insights (
  session_id text primary key references sessions(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade not null,
  focus text not null,
  analyzer_version text not null,
  analyzed_at timestamptz default now(),
  rescore integer,
  score_drift integer,
  hallucinations jsonb default '[]'::jsonb,
  rubric_gaps jsonb default '[]'::jsonb,
  bad_questions jsonb default '[]'::jsonb,
  flags text[] default '{}',
  coaching_notes text default '',
  error text default null,
  duration_ms integer default 0,
  resume_snapshot jsonb
);

create index if not exists idx_session_insights_user on session_insights(user_id);
create index if not exists idx_session_insights_focus on session_insights(focus);
create index if not exists idx_session_insights_analyzed_at on session_insights(analyzed_at);
create index if not exists idx_session_insights_flags on session_insights using gin(flags);

alter table session_insights enable row level security;
drop policy if exists "session_insights_select_own" on session_insights;
create policy "session_insights_select_own" on session_insights
  for select using (auth.uid() = user_id);

create table if not exists daily_quality_report (
  day date not null,
  focus text not null,
  sessions_analyzed integer not null default 0,
  avg_score_drift numeric default 0,
  hallucination_rate numeric default 0,
  flagged_question_count integer default 0,
  top_flags jsonb default '[]'::jsonb,
  top_weak_signals jsonb default '[]'::jsonb,
  generated_at timestamptz default now(),
  primary key (day, focus)
);

create index if not exists idx_daily_quality_report_day on daily_quality_report(day);
alter table daily_quality_report enable row level security;

-- ═══════════════════════════════════════════════════════
-- Quality v2 — resolution tracking + severity + AI digests
-- ═══════════════════════════════════════════════════════

-- Resolution workflow on every insight row.
-- status: open (default) | acknowledged | resolved | wont_fix
alter table session_insights add column if not exists resolution_status text default 'open';
alter table session_insights add column if not exists resolution_notes text default '';
alter table session_insights add column if not exists resolved_at timestamptz;
alter table session_insights add column if not exists resolved_by text;

-- Severity computed at write time:
--   high   — any hallucination, OR |score_drift| ≥ 10
--   medium — any flag, no hallucinations
--   low    — no flags (clean session)
alter table session_insights add column if not exists severity text default 'medium';

-- Resume snapshot threaded into the analyzer at run time (see migration
-- 0003). NULL when the session had no resume_version_id or the lookup
-- failed; otherwise a normalized ResumeForAnalyzer shape.
alter table session_insights add column if not exists resume_snapshot jsonb;

-- Structured per-focus analyzer metadata (AnalyzerMeta). Today carries
-- the campus-placement tier-aware CGPA calibration and the behavioral
-- STAR breakdown; new foci append optional sub-keys without a migration.
-- NULL on rows written before the column landed — readers MUST treat
-- missing as "no meta" rather than erroring out.
alter table session_insights add column if not exists meta jsonb;

create index if not exists idx_session_insights_status on session_insights(resolution_status);
create index if not exists idx_session_insights_severity on session_insights(severity);

-- Fix-outcome verification: nightly cron compares 7-day flag rate
-- before vs after the resolved_at timestamp. NULL until verdict
-- is computed (typically 7 days after resolution).
alter table session_insights add column if not exists fix_outcome jsonb;
-- Shape: { verdict: 'verified'|'no_change'|'regressed'|'insufficient_data',
--          delta: number, before_rate: number, after_rate: number,
--          before_count: int, after_count: int, computed_at: timestamp }

-- Daily AI-generated narrative digest. One row per day.
-- Generated by the cron after analyzers run. Idempotent re-generation
-- supported — the cron upserts on the day primary key.
create table if not exists daily_digests (
  day date primary key,
  generated_at timestamptz default now(),
  model text default '',
  fixes_summary text default '',          -- "5 sessions resolved today: ..."
  improvements_summary text default '',    -- "Behavioral STAR regex tightened (commit abc123)"
  patterns_summary text default '',        -- "Salary-neg AI over-quoting equity at senior tier"
  recommendations text default '',         -- actionable next steps
  raw_input jsonb default '{}'::jsonb,     -- audit: what we sent to the LLM
  error text default null
);

alter table daily_digests enable row level security;
-- No user-facing select — internal admin only via service role.

-- ═══════════════════════════════════════════════════════
-- Prompt revisions — A/B harness for live prompt changes
-- ═══════════════════════════════════════════════════════
-- Admin logs a marker each time they deploy a prompt change for a
-- focus. The cron measures the focus-wide flag-rate 7 days before vs
-- after the deployed_at timestamp and stores the outcome — same
-- mechanism as session-level fix_outcome but scoped to a whole focus.
create table if not exists prompt_revisions (
  id uuid primary key default gen_random_uuid(),
  focus text not null,
  description text not null,
  commit_sha text default '',
  deployed_at timestamptz not null default now(),
  deployed_by text default '',
  outcome jsonb,                  -- same shape as session_insights.fix_outcome
  created_at timestamptz default now()
);

create index if not exists idx_prompt_revisions_focus on prompt_revisions(focus);
create index if not exists idx_prompt_revisions_deployed_at on prompt_revisions(deployed_at);

alter table prompt_revisions enable row level security;
-- Internal admin only — accessed via service role.

-- ═══════════════════════════════════════════════════════
-- Quality recommendations — proactive fix suggestions
-- ═══════════════════════════════════════════════════════
-- The cron auto-generates fix recommendations after each run by
-- calling the same LLM as 'Generate fix plan' (so the dashboard isn't
-- the only way to see them). Persisted with status so admin can
-- triage: pending → in_progress → done / dismissed.
-- Dedup key: (target_file, title) — re-runs upsert rather than
-- creating duplicates each night.
create table if not exists quality_recommendations (
  id uuid primary key default gen_random_uuid(),
  dedup_key text not null unique,    -- normalized "<target_file>::<title>"
  priority text default 'medium',     -- high | medium | low
  title text not null,
  target_file text default '',
  change_description text default '',
  rationale text default '',
  affected_flags text[] default '{}',
  affected_focus text default '',     -- best-guess focus this targets
  file_grounded boolean default true,

  status text default 'pending',      -- pending | in_progress | done | dismissed
  status_notes text default '',
  status_updated_at timestamptz,
  status_updated_by text default '',

  first_seen_at timestamptz default now(),
  last_seen_at timestamptz default now(),
  seen_count integer default 1
);

create index if not exists idx_quality_recs_status on quality_recommendations(status);
create index if not exists idx_quality_recs_priority on quality_recommendations(priority);
create index if not exists idx_quality_recs_last_seen on quality_recommendations(last_seen_at);

alter table quality_recommendations enable row level security;

-- ═══════════════════════════════════════════════════════
-- 21. Salary offers — user-reported ground truth
--
-- Per-user post-session capture of "what offer did you get?". This is
-- the slow-burn moat for salary negotiation accuracy: every offer
-- reported here can be aggregated server-side to ground-truth our
-- per-(company, role, level, city) bands without the AB sampling bias
-- (people earning 3rd-quartile self-select to post on AB more than
-- 1st-quartile or 4th-quartile).
--
-- Privacy: rows are user-scoped under RLS. Only opt-in
-- may_share_aggregate=true rows are eligible to roll into shared
-- aggregates, and even those are only ever read in
-- bucket-of-≥5-rows form (k-anonymity floor) by the aggregator.
-- ═══════════════════════════════════════════════════════

create table if not exists salary_offers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,

  -- Offer dimensions (canonical lookup keys)
  company text not null,
  role text not null,
  level text not null,                   -- entry|mid|senior|lead|executive
  city text,                             -- job city (free text; resolved at read time)
  company_tier text,                     -- snapshot of resolved CompanyTier at insert time

  -- The number(s) — all in LPA (lakhs per annum). Nullable so partial
  -- self-reports (just total CTC) still produce useful signal.
  total_ctc_lpa numeric(8, 2) not null,
  base_lpa numeric(8, 2),
  variable_lpa numeric(8, 2),
  joining_bonus_lpa numeric(8, 2),
  equity_lpa numeric(8, 2),              -- annualized, for RSU-paying tiers

  -- Negotiation context (informs counter-offer playbook calibration)
  initial_offer_lpa numeric(8, 2),       -- what they offered first
  final_offer_lpa numeric(8, 2),         -- what was signed (may equal total_ctc_lpa)
  competing_offer_lpa numeric(8, 2),     -- the leverage offer, if any
  yoe_at_offer numeric(4, 1),            -- e.g. 4.5 = 4 yrs 6 mo
  outcome text not null,                 -- accepted|declined|negotiating|rescinded

  -- Source / verification
  has_written_letter boolean default false,
  letter_storage_path text,              -- supabase storage path; NULL until uploaded
  source text default 'self-reported',   -- self-reported|written-letter|verified

  -- Privacy / sharing
  may_share_aggregate boolean default false,
  notes text,

  reported_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_salary_offers_user on salary_offers(user_id);
create index if not exists idx_salary_offers_lookup on salary_offers(company, role, level);
create index if not exists idx_salary_offers_aggregate on salary_offers(company, role, level)
  where may_share_aggregate = true;

alter table salary_offers enable row level security;
drop policy if exists "Users manage own offers" on salary_offers;
create policy "Users manage own offers" on salary_offers
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── Service Usage Monitoring ──────────────────────────────────────────────────
-- Tracks TTS, LLM, and STT provider calls for cost and error-rate visibility.
-- logServiceUsage() in _shared.ts writes here; reads are ops/admin only.
create table if not exists service_usage (
  id            uuid         primary key default gen_random_uuid(),
  service       text         not null,
  endpoint      text,
  user_id       uuid         references profiles(id) on delete set null,
  status        text         not null
                             check (status in ('success','error','timeout','rate_limited')),
  latency_ms    integer,
  request_chars integer,
  response_bytes integer,
  error_message text,
  meta          jsonb,
  created_at    timestamptz  not null default now()
);
alter table service_usage enable row level security;
-- No user-facing RLS policy — service-role writes only.
create index if not exists idx_service_usage_service
  on service_usage(service, created_at desc);
create index if not exists idx_service_usage_user
  on service_usage(user_id, created_at desc);

