/* Session History canvas — fixture data.
   Pure mock-data harness (§5.1 escape hatch): crafted SessionHistoryItem
   arrays fed into the real SessionHistoryDesign / SessionReport components,
   no UI logic lives here. */
import type { SessionHistoryItem } from "@/SessionHistoryDesign";

export const FEW_SESSIONS: SessionHistoryItem[] = [
  {
    id: "few-1",
    type: "Behavioral",
    role: "Senior PM",
    company: "Razorpay",
    date: "2026-09-25T09:30:00Z",
    dateLabel: "2 days ago",
    duration: "38m",
    score: 82,
    delta: 5,
    topStrength: "Crisp STAR framing",
    topGap: "Quantify impact",
    questions: 7,
  },
  {
    id: "few-2",
    type: "Salary Neg.",
    role: "Senior PM",
    company: "Razorpay",
    date: "2026-09-18T18:00:00Z",
    dateLabel: "Last week",
    duration: "29m",
    score: 74,
    delta: -2,
    topStrength: "Anchored high, calm",
    topGap: "Equity literacy",
    questions: 6,
  },
];

export const RICH_SESSIONS: SessionHistoryItem[] = [
  {
    id: "rich-draft",
    type: "Behavioral",
    role: "Staff Engineer",
    company: "Flipkart",
    date: "2026-09-27T08:10:00Z",
    dateLabel: "Today, 8:10 AM",
    duration: "6m",
    score: 0,
    delta: 0,
    topStrength: "",
    topGap: "",
    questions: 0,
    draft: true,
  },
  {
    id: "rich-strong",
    type: "Behavioral",
    role: "Staff Engineer",
    company: "Flipkart",
    date: "2026-09-26T14:00:00Z",
    dateLabel: "Yesterday",
    duration: "44m",
    score: 88,
    delta: 7,
    topStrength: "Crisp STAR framing",
    topGap: "Quantify impact",
    coaching: {
      strength: { headline: "Crisp STAR framing", meaning: "Every answer had a clear situation → action → result arc." },
      gap: {
        headline: "Quantify impact",
        meaning: "Strong stories, but the outcome is rarely a number.",
        example: "Instead of \"it went well\", say \"cut review time from 3 days to 6 hours\".",
      },
    },
    focusMetrics: [
      { label: "STAR coverage", value: "92%", tone: "good" },
      { label: "Specificity", value: "Medium", tone: "watch" },
      { label: "Pacing", value: "On target", tone: "good" },
    ],
    questions: 8,
    difficulty: "Hard",
  },
  {
    id: "rich-solid",
    type: "System Design",
    role: "Staff Engineer",
    company: "PhonePe",
    date: "2026-09-24T11:00:00Z",
    dateLabel: "3 days ago",
    duration: "58m",
    score: 78,
    delta: 3,
    topStrength: "Tradeoff thinking",
    topGap: "Capacity math",
    questions: 5,
    difficulty: "Hard",
  },
  {
    id: "rich-mixed",
    type: "Salary Neg.",
    role: "Engineering Manager",
    company: "Swiggy",
    date: "2026-09-21T18:15:00Z",
    dateLabel: "6 days ago",
    duration: "31m",
    score: 70,
    delta: -1,
    topStrength: "Stayed calm under pressure",
    topGap: "Anchored too low",
    questions: 6,
  },
  {
    id: "rich-below",
    type: "Tech Screen",
    role: "Backend Engineer",
    company: "Zomato",
    date: "2026-09-15T15:00:00Z",
    dateLabel: "2 weeks ago",
    duration: "24m",
    score: 58,
    delta: -6,
    topStrength: "Clean syntax",
    topGap: "Edge-case coverage",
    focusMetrics: [
      { label: "Edge cases", value: "Missed 3", tone: "miss" },
      { label: "Complexity", value: "Not stated", tone: "watch" },
    ],
    questions: 4,
    difficulty: "Medium",
  },
  {
    id: "rich-incomplete",
    type: "Hiring Mgr",
    role: "Engineering Manager",
    company: "Cred",
    date: "2026-09-10T12:00:00Z",
    dateLabel: "3 weeks ago",
    duration: "4m",
    score: 0,
    delta: 0,
    topStrength: "",
    topGap: "",
    questions: 0,
    feedback: "Session ended before any answers were recorded.",
  },
  {
    id: "rich-behavioral-2",
    type: "Behavioral",
    role: "Staff Engineer",
    company: "Flipkart",
    date: "2026-09-05T09:00:00Z",
    dateLabel: "Last month",
    duration: "41m",
    score: 68,
    delta: -4,
    topStrength: "Authentic tone",
    topGap: "STAR S+T compression",
    questions: 8,
  },
  {
    id: "rich-campus",
    type: "Behavioral",
    role: "New Grad SWE",
    company: "Infosys",
    date: "2026-08-30T10:30:00Z",
    dateLabel: "Last month",
    duration: "33m",
    score: 76,
    delta: 2,
    topStrength: "Enthusiastic delivery",
    topGap: "Vague project ownership",
    focus: "campus-placement",
    questions: 6,
  },
  {
    id: "rich-hr",
    type: "HR Round",
    role: "Senior PM",
    company: "Razorpay",
    date: "2026-08-20T16:00:00Z",
    dateLabel: "5 weeks ago",
    duration: "22m",
    score: 81,
    delta: 4,
    topStrength: "Honest about tradeoffs",
    topGap: "Notice-period framing",
    questions: 5,
  },
];

export const PRELIMINARY_FIXTURE = {
  score: 61,
  topStrength: "Stayed structured under a rapid-fire panel",
  topWeakness: "Rushed the close on the compensation question",
  feedback:
    "You held a clear STAR shape through four of five answers — the panel format didn't rattle you. The comp question needed one more beat before answering.",
  role: "Senior PM",
  company: "Razorpay",
};
