/* Campus-placement flag → coaching-tip registry.
 *
 * Extracted from `campus-placement.ts` in v6.9. Each tip is keyed by
 * the flag name the analyzer emits; the analyzer's final step iterates
 * the produced flag set and joins the matching tips into
 * `result.coachingNotes`.
 *
 * Keeping the dictionary in its own module:
 *   - lets the analyzer file stay under the 1500-LOC ESLint warn line
 *   - makes a missing tip for a new flag trivially discoverable
 *   - sets up a future test (one assertion per flag) that catches
 *     additions to the analyzer that ship without a paired tip
 *
 * Order is preserved from the original if-chain for diff legibility —
 * the analyzer iterates the live flag set rather than the dictionary,
 * so insertion order here is documentation only.
 */

export const CAMPUS_FLAG_TIPS: Record<string, string> = {
  no_academic_project_discussed: "As a fresher, lead with your capstone or final-year project — it's your strongest evidence.",
  generic_passion_no_substance: "Replace 'I'm passionate about tech' with 'I built X using Y, here's what I learned.'",
  user_badmouthing_college: "Even if coursework was weak, frame it as 'I supplemented with self-study and projects' — never criticize professors.",
  project_no_tech_stack: "Always name the stack: language + framework + DB + deployment. 'I built it in Python, FastAPI, Postgres, deployed on Render' beats 'I built a web app.'",
  implausible_team_size: "College projects are typically 3-6 people. If you led 20, it was likely a college fest — frame the leadership separately from technical projects.",
  no_company_specific_research: "Spend 20 minutes on the careers page before each interview. Name a program, a value, or a recent launch — never just 'great culture'.",
  volunteered_academic_deficit: "Don't volunteer backlogs or low CGPA. If asked directly, say what happened in one sentence and pivot to what you did about it.",
  excessive_filler_words: "Replace fillers with a half-second pause. Recording one mock and counting your 'basically's is the fastest fix.",
  internship_unsubstantiated: "If you list an internship, be ready with: company, duration, mentor, what shipped, and a measurable outcome.",
  mti_pattern_detected: "Watch for Mother-Tongue-Influence phrasing that tier-1 recruiters flag: 'please reply' (not 'kindly revert back'), 'I have a question' (not 'doubt'), 'I'm Rahul' (not 'Myself Rahul'), 'discuss this' (not 'discuss about this'). Note: 'passed out 2024' is standard Indian English — no need to swap.",
  cgpa_low_no_framing: "If your CGPA is under 7, never state it bare. Use the 3-part frame: one-sentence honest reason → one piece of recent evidence (project / internship / hackathon) → forward-looking intent. Bare numbers below 7 stick in the interviewer's memory.",
  reverse_questions_declined: "Always have 2-3 reverse-questions ready: training program details, mentor structure, what the first 6 months look like, a specific point from the PPT. Saying 'no' to 'any questions for us?' tells the interviewer you didn't prepare.",
  weak_reverse_questions: "'What's the work culture?' isn't a real question — every interviewer hears it 20 times a day. Ask specific: 'What does a typical week look like for an SDE on your Trailhead team?' or 'You mentioned the new ABDM project in the PPT — would freshers rotate through it?'",
  bond_refusal: "Never refuse the bond outright in an on-campus TCS/Infosys/Wipro interview — it's an instant disqualifier. If concerned, ask: 'Could you walk me through the buyout terms and the typical reasons people exercise them?' Sounds informed, not resistant.",
  bond_unprepared: "Know the bond duration for your target company before the interview. Quick reference: TCS 2 years, Infosys 1 year, Wipro 15 months + ₹2L bond, Cognizant 1 year, HCL 1.5 years, Tech Mahindra / Capgemini / Accenture 1 year. Service-tier firms WILL ask.",
  attrition_risk_higher_studies: "If MBA / MS is a real 2-year plan, don't volunteer it in a service-tier campus interview — bonds recover training cost over 2 years and recruiters discount you immediately. If asked directly, frame as 'I'd like to first build a strong foundation here — higher studies is a future consideration, not a fixed timeline.'",
  relocation_refusal: "Pan-India service firms allocate across Mysore / Hyderabad / Chennai / Bhubaneswar / Coimbatore — flat refusal of relocation ends the conversation. If you have a genuine constraint, soften: 'I have a preference for Southern locations due to family — could you walk me through how allocation works?' Curiosity, not refusal.",
  shift_oncall_refusal: "Most service-tier and global-product India roles include rotational / US-shift coverage. Saying 'I can't do night shift' before understanding the cadence (every 8 weeks? Once a quarter? Only during incidents?) reads as inflexible. Ask first, decide later.",
  cliche_strength_weakness: "Drop 'perfectionist' and 'I work too hard' — every interviewer hears these 5x a day. Real weaknesses: 'I over-engineer when I should ship and iterate. I've started timeboxing my POCs to 2 days.' Specific, calibrated, with a real fix in progress.",
  tmay_resume_recital: "'Tell me about yourself' is NOT a resume read. Use the 60-second frame: one sentence on who you are → one strong project with a measurable outcome → one sentence on why this role. Skip 'as per my resume' — they already read it.",
  career_goal_vague: "'I see myself in a senior position' is the laziest possible answer to the 5-year question. Pick a specific role: 'SDE-2 with ownership of a backend service' / 'tech lead on a payments squad' / 'product specialist in fintech infra'. Specific = thoughtful; vague = unprepared.",
  hackathon_unsubstantiated: "If you mention a hackathon, lead with: theme + team size + duration + what you built + the rank/outcome. 'Smart India Hackathon 2023, 4-person team, built an OCR pipeline for railway tickets, finalist (top 5 of 80)' beats 'I did SIH.'",
  buzzword_soup: "Listing AI + ML + blockchain + IoT + web3 as interests without a single project reads as resume padding. Pick ONE — say 'I went deep on ML over my final year and built a 3-stage churn-prediction pipeline with XGBoost' — depth beats breadth in fresher interviews.",
  family_pressure_framing: "Never frame your career as parent-driven ('my parents wanted me to do engineering / join TCS'). Own the choice even if the original push came from family: 'I picked CS because the problem-solving clicked for me in 12th — I've been building projects since.' Recruiters select for ownership.",
  negative_company_compare: "Never trash another company — even a competitor, even one that rejected you. The interviewer notes 'will say negative things about us in 2 years.' If asked 'why us over X', name what excites you about THIS company, not what's wrong with X.",
  salary_expectation_inflated: "Campus fresher offers are typically non-negotiable and capped by tier (TCS/Infosys ≈ ₹3.5-4.5L, Indian product ≈ ₹6-15L, global product India ≈ ₹15-30L for fresher SDE). Quoting a number 2-3x above band tells recruiters you didn't do research. Either anchor to levels.fyi data or defer: 'I trust the standard fresher band — I'd like to learn more about the role first.'",
  salary_raised_too_early: "Don't bring up salary in the technical / first round. Wrong round = wrong priorities signal. Wait for HR / final round, or for the interviewer to raise it. If you genuinely don't know the band, ask after the technical conversation has finished: 'I'd love to understand the comp structure — when's the right time to discuss?'",
  portfolio_absent_for_claim: "Drop a GitHub link / live demo URL whenever you narrate a project. 'Source is on my GitHub at github.com/username/repo' or 'live demo at xyz.vercel.app' adds 10x credibility versus a verbal claim — recruiters can check it in 30 seconds.",
  active_backlog_evasion: "Service-tier firms (TCS/Infosys/Wipro/Cognizant) auto-reject anyone with active backlogs — and hedging reads the same as having one. State your exact standing: 'Zero active backlogs; one supplementary cleared in 2nd year.' Crisp facts beat dodging.",
  branch_jump_thin_narrative: "Non-CS branch into SDE? Build the bridge upfront: a named course (CS50 / Striver / NPTEL), 3-4 self-built projects, and one sentence on what clicked. 'I'm Mech, did CS50 + Striver SDE Sheet, built 4 projects, applied because systems thinking translates.' Owns the switch instead of hiding it.",
  ppt_recall_absent: "Always reference the pre-placement talk: a speaker name, a recent launch, a program ('Infosys Springboard', 'Wipro Turbo', 'TCS Digital'). Even one mention proves you listened — interviewers heavily weight this on campus.",
  coding_round_score_undefended: "Defend a low coding score with one honest + one recent-evidence sentence: 'Time pressure on the last problem; since then I've solved 200+ on Leetcode, currently Knight rated.' Owning the gap with proof beats excusing it.",
  parallel_exam_prep_disclosed: "Don't volunteer GATE / CAT / UPSC parallel prep in service-tier interviews — recruiters discount you as 1-2 year attrition risk. If asked directly, frame as: 'I'd like to first build a strong foundation here; longer-term plans are flexible and not in a fixed window.'",
  tier_3_overcompensation: "Calibrate achievement claims to verifiable detail. 'Top 5 in my college hackathon (40 teams, 36 hours, built X)' lands; 'national hackathon winner' invites a one-question verification drill you can't pass. Specificity beats grandiosity.",
  fyp_solo_claim_vs_team: "Be precise on individual contribution in team projects. 'In our 4-person FYP, I owned the backend (FastAPI + Postgres); teammates handled the React frontend and the ML model.' Mixing 'I built' with 'we presented' invites a 'who did what' drill.",
  stipend_dodge: "Stipend is a routine probe — state numbers cleanly even if small. '₹25K/month at the startup; unpaid academic internship at the lab under Prof. X.' Hedging reads as fabrication, even when the internship was real.",
  memorized_self_intro: "'Good morning sir, first of all thank you for this wonderful opportunity, coming to my introduction' is the YouTube template every panel has heard 500 times. Open with one sentence on who you are + one strong project line + why this role. Verbatim templates flag as no-thought.",
  aptitude_puzzle_refusal: "Never refuse a live puzzle / DSA / estimation flat. Narrate: 'Let me think out loud — I'll start with the brute force, then optimize.' Interviewers grade approach more than the final answer; saying 'I can't think under pressure' kills the rest of the round.",
  onsite_opportunity_premature: "Don't bring up onsite / US deputation in the first 2-3 turns — service-tier recruiters read it as offer-shopping. Save it for HR / post-offer. If genuinely curious, phrase as 'I'd love to understand how growth and global rotation work over the first 2-3 years.'",
  nepotism_reference: "Never volunteer that a relative / family-friend works at the company — even as small-talk. It activates explicit anti-nepotism filters at Indian firms and is forbidden at PSU / consulting / Big-4. If BGV surfaces it later, that's fine; mentioning it unsolicited isn't.",
  inhand_vs_ctc_confusion: "Learn the CTC ladder before the interview: CTC = fixed + variable + joining bonus + RSU + benefits. In-hand ≈ 70-78% of fixed after tax + EPF + professional tax. Asking 'isn't CTC the in-hand' tells recruiters you didn't prepare for the offer conversation.",
  code_on_paper_freeze: "Practice writing 15-20 line solutions on paper / chat / a doc during prep — at least 10 problems before any campus drive. 'I can only code in an IDE' tells the interviewer you've memorized templates, not internalized logic. Even rough pseudocode beats refusal.",
  resume_date_inconsistency: "Internship / project windows must not overlap unless explicitly part-time and disclosed. Two full-time ranges that overlap trip BGV instantly and read as fabrication. Pull the resume, fix the months, and rehearse the corrected timeline in one breath.",
  degree_branch_inconsistency: "Pick the exact branch name on your transcript and stick with it across the whole conversation. If you have a minor / dual-degree, say so once: 'CSE major with an AIML minor.' Drifting between 'I'm in CSE' and 'I'm in AIML' reads as confusion or fabrication.",
  claimed_internship_not_in_resume: "Every company you mention in the interview must already appear on your uploaded resume. BGV uses the resume as ground truth — narrating a role that isn't listed reads as fabrication and is the #1 instant-disqualifier in Indian campus rounds. Update the resume before the next session, or only narrate companies you've already listed.",
  branch_mismatch_with_resume: "Your resume's degree field is the BGV-checked source of truth. If you spoke about a different branch than what's on your resume, frame it explicitly: 'My resume lists Mechanical — I've been doing CS50, Striver SDE Sheet, and projects on the side, which is why I'm targeting SDE roles.' Owning the bridge beats a silent verbal swap.",
  grad_year_mismatch_with_resume: "Your stated graduation year and the year on your resume must match within a year — BGV pulls the year off your provisional degree / transcript. If you're an extended-semester passout, state it once and stick to it: 'I graduated in 2024 — completed after one supplementary in extended semester.' Drifting between two years in the same interview reads as fabrication.",
  college_mismatch_with_resume: "Name the exact college on your resume — Indian campus BGV cross-checks the degree certificate, and Tier-1-sounding swaps (e.g. saying 'IIT' when the resume lists 'NIT') are an instant disqualifier. If you transferred, say it once: 'Started at NIT Surat, transferred to NIT Trichy in 2nd year, both reflected on the resume.'",
  internship_duration_mismatch_with_resume: "Your resume's internship dates (and the matching offer / relieving letter) are what BGV pulls — never round 3 months up to 'six months' to sound stronger. If you genuinely extended an internship, state it cleanly: 'Initial 3-month internship, extended by another 3 months — both reflected on the relieving letter.' Specific timelines beat inflated round numbers.",
  college_cgpa_policy_acknowledged: "Good — you anchored your CGPA against the college / TPO internal cutoff. Indian recruiters respect this framing because internal college gatekeeping is real (tier-2/3 colleges enforce 6.5–7.0 bars even when firm cutoffs are 6.0). Keep using it when relevant: 'My college's TPO cutoff is 7.0; my CGPA is 7.2' lands much better than a bare 7.2.",
  mid_session_questions_present: "Good — you asked substantive questions mid-interview (tech stack / mentor / growth track), not just at the closing 'any questions?' slot. Indian campus recruiters weight curiosity across the whole conversation; an empty closer after smart mid-session asks reads as 'thoroughly satisfied', not 'unprepared'.",
  shipped_to_prod_context: "Strong — anchoring a project in production / active-users / merged-PRs evidence beats a bare 'I built X' every time. At product-grade panels (Google / Razorpay / TCS Digital), 'shipped to prod, 200 DAU' is recognised as higher credibility than a GitHub URL alone. Keep this phrasing — it's the rubric-matched answer.",
  location_agnostic_signal: "Good — proactively stating you're open to any location / pan-India removes a friction point the panel would otherwise probe. At service-tier (TCS / Infosys / Wipro / Cognizant) this is table-stakes; at Digital tracks it's a positive differentiator. Keep volunteering it.",
  short_screening_session_acknowledged: "This was a short screening-format conversation, not a full panel. The rubric was relaxed accordingly — no penalty for a missing closing 'any questions for us?' slot or a single bond mention. Treat the next round as the deeper rubric.",
  internship_company_unrecognized: "When naming an internship company, use the full, recognised legal name (e.g. 'Razorpay Software Pvt Ltd' / 'Infosys BPM'). If the firm is small or local, briefly anchor it: 'a 12-person fintech startup in Bangalore that powers UPI for X bank.' Vague unrecognised names invite a verification drill that's hard to defend.",
  cgpa_mismatch_with_resume: "Your CGPA on the resume is the BGV-checked number — recruiters cross-reference it against your transcript. Stating a different CGPA verbally (even rounded up by 1 point) reads as fabrication. If your latest semester moved the average, say so explicitly: 'My resume shows 7.2 from last semester; current cumulative is 7.4 after this semester's results.' Specificity beats inflation.",
  // New flags added in v6.11 fixes
  availability_discussed: "Good — you covered your availability / joining date clearly. Service-tier panels (TCS / Infosys / Wipro) flag candidates who leave this unaddressed; a crisp 'I can join from [date], confirming with college no-dues in the last week of [month]' closes the loop.",
  portfolio_satisfied_by_resume: "Your resume already includes a GitHub / portfolio link, which satisfies the portfolio requirement. Recruiters can verify your work before the interview — you don't have to re-share the URL verbally, but mentioning it once ('my projects are on my GitHub profile, which is on the resume') reinforces the signal.",
  combined_compliance_refusal: "You refused both the service bond and the shift / on-call obligation. At TCS / Infosys / Wipro / Cognizant, both are non-negotiable conditions of the role offer — refusing either alone is a red flag; refusing both ends the loop. If you have a genuine constraint, name it once and frame it as a question: 'I'd need to understand the shift rotation cadence before committing — is there flexibility for the first year?' Never lead with a flat refusal.",
};
