/* HireStepX — Programmatic SEO source-of-truth
 *
 * Single source for the auto-generated company × focus landing pages.
 * Each tuple becomes one indexable URL like
 *   /companies/razorpay/pm-interview-questions
 * with content templated from the curated question bank + role-aware
 * sample answers.
 *
 * The strategy: don't try to outrank AmbitionBox / Glassdoor on
 * generic queries ("razorpay interview questions"). Own the long-tail
 * intent layer they underserve — "razorpay PM case study practice",
 * "tcs ninja interview practice 2026 freshers" — where the searcher
 * wants to PRACTICE answering, not just see a list.
 *
 * Curation rules:
 *   - Only (company × focus) tuples with ≥3 entries in the curated
 *     question bank get a page. Thin pages get penalized by Google's
 *     Helpful Content update.
 *   - Each combo carries a hand-written intro paragraph + a hand-
 *     picked framework hint. Auto-generated boilerplate WILL get
 *     deindexed.
 *   - Page slugs use kebab-case. Companies normalised to lowercase.
 */

import type { CompanyKey, FocusArea, RoleFamily } from "./interview-question-bank";

export interface SeoPage {
  /* URL path under /companies/. Generated, not user-editable. */
  slug: string;
  /* What a real candidate would search to land on this page. The H1
     of the rendered page mirrors this query. */
  searchPhrase: string;
  /* Page-specific company. */
  company: CompanyKey;
  /* Optional role-family scope. When undefined, page covers the focus
     across all roles at the company (broader, less competitive). */
  roleFamily?: RoleFamily;
  /* The interview-focus area the page is built around. */
  focus: FocusArea;
  /* Hand-written intro paragraph — distinguishes this page from a
     templated generic one. Avoids the Helpful Content penalty. */
  intro: string;
  /* Framework name + one-line summary, surfaced inline. */
  framework: { name: string; summary: string };
  /* Keywords for the meta description. Mostly informational; Next's
     metadata API doesn't weight these any more, but they pair well
     with OG descriptions. */
  metaKeywords: string[];
  /* Optional priority hint for sitemap.xml — top-tier pages get
     higher priority (0.8), niche combos lower (0.4). */
  sitemapPriority?: number;
}

/* The curated set. Generated by hand from the question bank — every
   (company × focus) here has ≥3 backing questions. */
export const SEO_PAGES: SeoPage[] = [
  /* ── Flipkart ──────────────────────────────────────────────── */
  {
    slug: "flipkart-pm-interview-questions",
    searchPhrase: "Flipkart Product Manager Interview Questions",
    company: "flipkart", roleFamily: "pm", focus: "case-study",
    intro: "Flipkart's PM rounds open with an ongoing problem from a real vertical — typically grocery, fashion, or BBD-scale logistics. Expect detailed probes on metrics, hypothesis structure, and prioritisation. The interviewers don't want frameworks recited at them; they want you to use a framework to drive to a recommendation.",
    framework: { name: "CIRCLES", summary: "Comprehend → Identify customer → Report needs → Cut prioritise → List solutions → Evaluate → Summarise." },
    metaKeywords: ["flipkart pm interview", "flipkart product manager", "flipkart case study", "flipkart interview practice"],
    sitemapPriority: 0.9,
  },
  {
    slug: "flipkart-sde-interview-questions",
    searchPhrase: "Flipkart Software Engineer Interview Questions",
    company: "flipkart", roleFamily: "swe", focus: "system-design",
    intro: "Flipkart engineering loves India-specific constraints — tier-3 pincodes, monsoon delivery, kirana partnerships. Their bar for SDE-2/3 system design is real: you'll be asked to design at 10x current scale and defend trade-offs explicitly.",
    framework: { name: "Capacity-first design", summary: "Start with QPS + storage estimates → reads/writes ratio → bottlenecks → solution → cost." },
    metaKeywords: ["flipkart sde interview", "flipkart system design", "flipkart software engineer", "flipkart technical interview"],
    sitemapPriority: 0.9,
  },

  /* ── Razorpay ──────────────────────────────────────────────── */
  {
    slug: "razorpay-engineering-interview-questions",
    searchPhrase: "Razorpay Engineering Interview Questions",
    company: "razorpay", roleFamily: "swe", focus: "system-design",
    intro: "Razorpay engineering rounds love production scenarios — UPI failure spikes, NPCI rate limits, settlement reconciliation, idempotent payment retries. Be specific. Generic 'I'd add caching' answers don't land here; they want to know which cache, what TTL, what happens on cache stampede.",
    framework: { name: "Reliability-first", summary: "Failure modes first → circuit breakers + idempotency → eventual consistency → reconciliation paths → monitoring." },
    metaKeywords: ["razorpay engineering interview", "razorpay sde", "razorpay system design", "razorpay payments interview"],
    sitemapPriority: 0.9,
  },
  {
    slug: "razorpay-pm-interview-questions",
    searchPhrase: "Razorpay Product Manager Interview Questions",
    company: "razorpay", roleFamily: "pm", focus: "case-study",
    intro: "Razorpay PM interviews skew operational. Expect questions about pricing for new merchant tiers, expansion to D2C brands, or feature priority for scale. Indian fintech context matters — knowing UPI vs cards economics is implicitly assumed.",
    framework: { name: "Pricing-first PM", summary: "Customer segment → willingness-to-pay → competitor anchor → price ladder → roll-out." },
    metaKeywords: ["razorpay pm interview", "razorpay product manager", "razorpay fintech interview"],
    sitemapPriority: 0.85,
  },

  /* ── Swiggy ────────────────────────────────────────────────── */
  {
    slug: "swiggy-pm-interview-questions",
    searchPhrase: "Swiggy Product Manager Interview Questions",
    company: "swiggy", roleFamily: "pm", focus: "case-study",
    intro: "Swiggy PM rounds heavily test marketplace dynamics — restaurant partner economics, delivery-partner availability, demand-supply imbalance, dine-in vs delivery trade-offs. Expect at least one question that requires you to think about 3-sided economics.",
    framework: { name: "Marketplace prioritisation", summary: "Identify the constrained side → unit economics → growth lever → defensibility." },
    metaKeywords: ["swiggy pm interview", "swiggy product manager", "swiggy case study", "swiggy marketplace interview"],
    sitemapPriority: 0.85,
  },

  /* ── Zomato ────────────────────────────────────────────────── */
  {
    slug: "zomato-product-interview-questions",
    searchPhrase: "Zomato Product Interview Questions",
    company: "zomato", roleFamily: "pm", focus: "case-study",
    intro: "Zomato interviews lean on real product diagnostics. Restaurant ratings are dropping in tier-2 cities — diagnose. Delivery times are climbing — root-cause. The format rewards candidates who can decompose ambiguity quickly.",
    framework: { name: "Diagnose framework", summary: "Define metric → segment by axis (geo/cohort/time) → form hypothesis → test → recommend." },
    metaKeywords: ["zomato pm interview", "zomato product manager", "zomato case study"],
    sitemapPriority: 0.8,
  },

  /* ── PhonePe ───────────────────────────────────────────────── */
  {
    slug: "phonepe-engineering-interview-questions",
    searchPhrase: "PhonePe Engineering Interview Questions",
    company: "phonepe", roleFamily: "swe", focus: "system-design",
    intro: "PhonePe engineering rounds are scale-obsessed. 100M daily UPI transactions is the implicit baseline. Every answer should explicitly address throughput, p99 latency, and cost at India scale. 'It depends' is the right default starting position.",
    framework: { name: "Scale-first design", summary: "QPS at peak → storage growth → consistency model → caching tiers → cost per million." },
    metaKeywords: ["phonepe engineering", "phonepe sde interview", "phonepe system design", "phonepe upi interview"],
    sitemapPriority: 0.85,
  },

  /* ── Paytm ─────────────────────────────────────────────────── */
  {
    slug: "paytm-engineering-interview-questions",
    searchPhrase: "Paytm Engineering Interview Questions",
    company: "paytm", roleFamily: "swe", focus: "system-design",
    intro: "Paytm engineering interviews mix scale + abuse-prevention. Cashback systems, fraud detection, and merchant payouts all involve adversarial users. Be ready for 'how do you prevent X' questions where X is explicitly a fraud pattern.",
    framework: { name: "Adversarial design", summary: "Threat model → detection signals → mitigation tiers → false-positive cost." },
    metaKeywords: ["paytm engineering interview", "paytm sde", "paytm system design", "paytm fintech interview"],
    sitemapPriority: 0.8,
  },

  /* ── TCS ───────────────────────────────────────────────────── */
  {
    slug: "tcs-ninja-interview-questions",
    searchPhrase: "TCS Ninja Interview Questions for 2026 Freshers",
    company: "tcs", roleFamily: "swe", focus: "technical",
    intro: "TCS Ninja and Digital tracks lean heavily on CS fundamentals — OOP, OS, DBMS, basic SQL. Expect rapid-fire questions, not deep dives. Final-year project explanation gets 5-6 follow-ups; be ready to defend architecture decisions you may have made hurriedly months ago.",
    framework: { name: "STAR for technical", summary: "Situation (project context) → Task (your specific role) → Action (what you actually built) → Result (measurable outcome)." },
    metaKeywords: ["tcs ninja interview", "tcs digital interview", "tcs fresher interview", "tcs technical interview", "tcs interview questions 2026"],
    sitemapPriority: 0.95,
  },
  {
    slug: "tcs-hr-round-questions",
    searchPhrase: "TCS HR Round Interview Questions",
    company: "tcs", roleFamily: "behavioral", focus: "hr",
    intro: "TCS HR rounds are formal, process-oriented, and predictable. The interviewer follows a script — relocation willingness, salary expectations, why TCS over peers, 5-year goals. Authenticity beats memorised answers; be specific about why you're choosing TCS.",
    framework: { name: "PAR for HR", summary: "Problem (their question's underlying concern) → Answer (your direct response) → Reassurance (why you're not a flight risk)." },
    metaKeywords: ["tcs hr interview", "tcs hr round", "tcs hr questions", "tcs interview hr"],
    sitemapPriority: 0.85,
  },

  /* ── Infosys ───────────────────────────────────────────────── */
  {
    slug: "infosys-campus-interview-questions",
    searchPhrase: "Infosys Campus Interview Questions for Freshers",
    company: "infosys", roleFamily: "behavioral", focus: "campus-placement",
    intro: "Infosys campus rounds dwell on the academic project — 5-6 follow-ups on architecture, your specific contribution, and design trade-offs. The interviewer will ask 'why did you choose React over Angular?' even if your team made the call collectively. Have a real reason ready.",
    framework: { name: "Project storytelling", summary: "Context (what + why) → Your contribution (specific tasks) → Trade-offs (what you considered but didn't pick) → Outcome (measurable impact)." },
    metaKeywords: ["infosys campus interview", "infosys fresher interview", "infosys interview questions", "infosys placement"],
    sitemapPriority: 0.9,
  },

  /* ── Google ────────────────────────────────────────────────── */
  {
    slug: "google-india-engineering-interview-questions",
    searchPhrase: "Google India Engineering Interview Questions",
    company: "google", roleFamily: "swe", focus: "system-design",
    intro: "Google's SWE rounds prize first-principles thinking and explicit trade-off articulation. Always discuss what you're approximating. The bar-raiser will probe your assumptions with 'what if X were 100x larger?' — your answer reveals depth or its absence.",
    framework: { name: "First-principles design", summary: "What's the actual constraint? → Without prior solutions, what's the simplest correct approach? → Trade-offs at scale → Approximations that matter." },
    metaKeywords: ["google india interview", "google sde interview", "google engineering interview", "google system design"],
    sitemapPriority: 0.85,
  },
  {
    slug: "google-pm-interview-questions",
    searchPhrase: "Google Product Manager Interview Questions",
    company: "google", roleFamily: "pm", focus: "case-study",
    intro: "Google PM interviews favour candidates who decompose ambiguity quickly and don't get attached to their first answer. India-specific products (YouTube, GPay, Search-in-India) come up — know the local nuances vs the global product.",
    framework: { name: "PM CIRCLES", summary: "Comprehend the problem → Identify the user → Report their needs → Cut by impact → List solutions → Evaluate → Summarise." },
    metaKeywords: ["google pm interview", "google product manager", "google case study"],
    sitemapPriority: 0.85,
  },

  /* ── Amazon ────────────────────────────────────────────────── */
  {
    slug: "amazon-leadership-principles-interview",
    searchPhrase: "Amazon Leadership Principles Interview Questions",
    company: "amazon", roleFamily: "behavioral", focus: "behavioral",
    intro: "Amazon rounds map every behavioural answer to one of the 16 Leadership Principles. Be explicit about which principle your story illustrates — 'this is a Customer Obsession story because…' Bar-raisers reward this signposting.",
    framework: { name: "STAR + LP signposting", summary: "Pick the LP → Situation that highlights it → Task → Action (your specific behaviour, not the team's) → Result (data) → Brief reflection on what you'd do differently." },
    metaKeywords: ["amazon leadership principles", "amazon behavioral interview", "amazon star interview", "amazon lp interview"],
    sitemapPriority: 0.9,
  },
  {
    slug: "amazon-system-design-interview-questions",
    searchPhrase: "Amazon System Design Interview Questions",
    company: "amazon", roleFamily: "swe", focus: "system-design",
    intro: "Amazon SDE-2/3 system design rounds lean operational — design Prime's recommendation engine, the order-fulfilment pipeline, or a scale-resilient cart. Bar-raiser will probe failure modes aggressively. Be ready for 'what happens if this region goes down?'",
    framework: { name: "Operational design", summary: "Functional requirements → non-functional (latency, availability) → API contracts → data model → component diagram → failure modes + recovery." },
    metaKeywords: ["amazon system design", "amazon sde interview", "amazon technical interview"],
    sitemapPriority: 0.85,
  },

  /* ── Salary negotiation ─────────────────────────────────────── */
  {
    slug: "salary-negotiation-india-tech",
    searchPhrase: "Salary Negotiation Practice for Indian Tech Roles",
    company: "razorpay", focus: "salary-negotiation",
    intro: "Salary negotiation is a multi-phase conversation, not a one-shot ask. Indian tech rounds open with a soft anchor ('this is competitive for your level'), then test whether you push back with structure or just accept. Naming a specific number — anchoring first — correlates with higher final offers.",
    framework: { name: "BATNA-first negotiation", summary: "Know your walk-away → anchor first with a specific number → cite market data → tier the package (base / variable / equity / signing / benefits) → never accept on the first call." },
    metaKeywords: ["salary negotiation india", "salary negotiation tech", "ctc negotiation india", "indian tech salary negotiation"],
    sitemapPriority: 0.9,
  },
];

/** Lookup helper. */
export function getSeoPageBySlug(slug: string): SeoPage | undefined {
  return SEO_PAGES.find((p) => p.slug === slug);
}

/** All slugs for static-params generation in Next.js. */
export function getAllSeoSlugs(): string[] {
  return SEO_PAGES.map((p) => p.slug);
}
