/* HireStepX — Programmatic SEO source-of-truth
 *
 * Single source for the auto-generated company × focus landing pages.
 * Each tuple becomes one indexable URL like
 *   /companies/razorpay/pm-interview-questions
 * with content templated from the curated question bank + role-aware
 * sample answers.
 *
 * The strategy: don't try to outrank AmbitionBox / Glassdoor on
 * generic queries ("razorpay interview questions"). Own the long-tail
 * intent layer they underserve — "razorpay PM case study practice",
 * "tcs ninja interview practice 2026 freshers" — where the searcher
 * wants to PRACTICE answering, not just see a list.
 *
 * Curation rules:
 *   - Only (company × focus) tuples with ≥3 entries in the curated
 *     question bank get a page. Thin pages get penalized by Google's
 *     Helpful Content update.
 *   - Each combo carries a hand-written intro paragraph + a hand-
 *     picked framework hint. Auto-generated boilerplate WILL get
 *     deindexed.
 *   - Page slugs use kebab-case. Companies normalised to lowercase.
 */

import type { CompanyKey, FocusArea, RoleFamily } from "./interview-question-bank";

export interface SeoPage {
  /* URL path under /companies/. Generated, not user-editable. */
  slug: string;
  /* What a real candidate would search to land on this page. The H1
     of the rendered page mirrors this query. */
  searchPhrase: string;
  /* Page-specific company. */
  company: CompanyKey;
  /* Optional role-family scope. When undefined, page covers the focus
     across all roles at the company (broader, less competitive). */
  roleFamily?: RoleFamily;
  /* The interview-focus area the page is built around. */
  focus: FocusArea;
  /* Hand-written intro paragraph — distinguishes this page from a
     templated generic one. Avoids the Helpful Content penalty. */
  intro: string;
  /* Framework name + one-line summary, surfaced inline. */
  framework: { name: string; summary: string };
  /* Keywords for the meta description. Mostly informational; Next's
     metadata API doesn't weight these any more, but they pair well
     with OG descriptions. */
  metaKeywords: string[];
  /* Optional priority hint for sitemap.xml — top-tier pages get
     higher priority (0.8), niche combos lower (0.4). */
  sitemapPriority?: number;
  /* Optional ordered steps in the company's hiring process.
     Rendered as a numbered list under "Recruitment Process". */
  recruitmentSteps?: string[];
  /* Optional descriptions of each interview round at this company.
     Rendered as a numbered list under "Interview Rounds". */
  interviewRounds?: string[];
}

/* The curated set. Generated by hand from the question bank — every
   (company × focus) here has ≥3 backing questions. */
export const SEO_PAGES: SeoPage[] = [
  /* ── Flipkart ──────────────────────────────────────────────── */
  {
    slug: "flipkart-pm-interview-questions",
    searchPhrase: "Flipkart Product Manager Interview Questions",
    company: "flipkart", roleFamily: "pm", focus: "case-study",
    intro: "Flipkart's PM rounds open with an ongoing problem from a real vertical — typically grocery, fashion, or BBD-scale logistics. Expect detailed probes on metrics, hypothesis structure, and prioritisation. The interviewers don't want frameworks recited at them; they want you to use a framework to drive to a recommendation.",
    framework: { name: "CIRCLES", summary: "Comprehend → Identify customer → Report needs → Cut prioritise → List solutions → Evaluate → Summarise." },
    metaKeywords: ["flipkart pm interview", "flipkart product manager", "flipkart case study", "flipkart interview practice"],
    sitemapPriority: 0.9,
  },
  {
    slug: "flipkart-sde-interview-questions",
    searchPhrase: "Flipkart Software Engineer Interview Questions",
    company: "flipkart", roleFamily: "swe", focus: "system-design",
    intro: "Flipkart engineering loves India-specific constraints — tier-3 pincodes, monsoon delivery, kirana partnerships. Their bar for SDE-2/3 system design is real: you'll be asked to design at 10x current scale and defend trade-offs explicitly.",
    framework: { name: "Capacity-first design", summary: "Start with QPS + storage estimates → reads/writes ratio → bottlenecks → solution → cost." },
    metaKeywords: ["flipkart sde interview", "flipkart system design", "flipkart software engineer", "flipkart technical interview"],
    sitemapPriority: 0.9,
  },

  /* ── Razorpay ──────────────────────────────────────────────── */
  {
    slug: "razorpay-engineering-interview-questions",
    searchPhrase: "Razorpay Engineering Interview Questions",
    company: "razorpay", roleFamily: "swe", focus: "system-design",
    intro: "Razorpay engineering rounds love production scenarios — UPI failure spikes, NPCI rate limits, settlement reconciliation, idempotent payment retries. Be specific. Generic 'I'd add caching' answers don't land here; they want to know which cache, what TTL, what happens on cache stampede.",
    framework: { name: "Reliability-first", summary: "Failure modes first → circuit breakers + idempotency → eventual consistency → reconciliation paths → monitoring." },
    metaKeywords: ["razorpay engineering interview", "razorpay sde", "razorpay system design", "razorpay payments interview"],
    sitemapPriority: 0.9,
  },
  {
    slug: "razorpay-pm-interview-questions",
    searchPhrase: "Razorpay Product Manager Interview Questions",
    company: "razorpay", roleFamily: "pm", focus: "case-study",
    intro: "Razorpay PM interviews skew operational. Expect questions about pricing for new merchant tiers, expansion to D2C brands, or feature priority for scale. Indian fintech context matters — knowing UPI vs cards economics is implicitly assumed.",
    framework: { name: "Pricing-first PM", summary: "Customer segment → willingness-to-pay → competitor anchor → price ladder → roll-out." },
    metaKeywords: ["razorpay pm interview", "razorpay product manager", "razorpay fintech interview"],
    sitemapPriority: 0.85,
  },

  /* ── Swiggy ────────────────────────────────────────────────── */
  {
    slug: "swiggy-pm-interview-questions",
    searchPhrase: "Swiggy Product Manager Interview Questions",
    company: "swiggy", roleFamily: "pm", focus: "case-study",
    intro: "Swiggy PM rounds heavily test marketplace dynamics — restaurant partner economics, delivery-partner availability, demand-supply imbalance, dine-in vs delivery trade-offs. Expect at least one question that requires you to think about 3-sided economics.",
    framework: { name: "Marketplace prioritisation", summary: "Identify the constrained side → unit economics → growth lever → defensibility." },
    metaKeywords: ["swiggy pm interview", "swiggy product manager", "swiggy case study", "swiggy marketplace interview"],
    sitemapPriority: 0.85,
  },

  /* ── Zomato ────────────────────────────────────────────────── */
  {
    slug: "zomato-product-interview-questions",
    searchPhrase: "Zomato Product Interview Questions",
    company: "zomato", roleFamily: "pm", focus: "case-study",
    intro: "Zomato interviews lean on real product diagnostics. Restaurant ratings are dropping in tier-2 cities — diagnose. Delivery times are climbing — root-cause. The format rewards candidates who can decompose ambiguity quickly.",
    framework: { name: "Diagnose framework", summary: "Define metric → segment by axis (geo/cohort/time) → form hypothesis → test → recommend." },
    metaKeywords: ["zomato pm interview", "zomato product manager", "zomato case study"],
    sitemapPriority: 0.8,
  },

  /* ── PhonePe ───────────────────────────────────────────────── */
  {
    slug: "phonepe-engineering-interview-questions",
    searchPhrase: "PhonePe Engineering Interview Questions",
    company: "phonepe", roleFamily: "swe", focus: "system-design",
    intro: "PhonePe engineering rounds are scale-obsessed. 100M daily UPI transactions is the implicit baseline. Every answer should explicitly address throughput, p99 latency, and cost at India scale. 'It depends' is the right default starting position. PhonePe processes 1B+ transactions per month and their system design questions are grounded in that reality — UPI flows, reconciliation pipelines, and high-availability for India's payment infrastructure.",
    framework: { name: "Scale-first design", summary: "QPS at peak → storage growth → consistency model → caching tiers → cost per million." },
    metaKeywords: ["phonepe engineering", "phonepe sde interview", "phonepe system design", "phonepe upi interview", "phonepe technical interview 2026"],
    sitemapPriority: 0.85,
    interviewRounds: [
      "Online Assessment (60 min): 2 DSA problems — typically medium-hard. Arrays, graphs, or DP.",
      "Technical Round 1 (60 min): DSA + architecture discussion. Expect follow-up on time/space complexity.",
      "Technical Round 2 / System Design (60 min): Design a payment system, notification engine, or settlement pipeline.",
      "Behavioral Round (45 min): Values + ownership stories. PhonePe values 'builder mindset' — prepare examples of initiative.",
    ],
  },

  /* ── Paytm ─────────────────────────────────────────────────── */
  {
    slug: "paytm-engineering-interview-questions",
    searchPhrase: "Paytm Engineering Interview Questions",
    company: "paytm", roleFamily: "swe", focus: "system-design",
    intro: "Paytm engineering interviews mix scale + abuse-prevention. Cashback systems, fraud detection, and merchant payouts all involve adversarial users. Be ready for 'how do you prevent X' questions where X is explicitly a fraud pattern.",
    framework: { name: "Adversarial design", summary: "Threat model → detection signals → mitigation tiers → false-positive cost." },
    metaKeywords: ["paytm engineering interview", "paytm sde", "paytm system design", "paytm fintech interview"],
    sitemapPriority: 0.8,
  },

  /* ── TCS ───────────────────────────────────────────────────── */
  {
    slug: "tcs-ninja-interview-questions",
    searchPhrase: "TCS Ninja Interview Questions for 2026 Freshers",
    company: "tcs", roleFamily: "swe", focus: "technical",
    intro: "TCS Ninja and Digital tracks lean heavily on CS fundamentals — OOP, OS, DBMS, basic SQL. Expect rapid-fire questions, not deep dives. Final-year project explanation gets 5-6 follow-ups; be ready to defend architecture decisions you may have made hurriedly months ago.",
    framework: { name: "STAR for technical", summary: "Situation (project context) → Task (your specific role) → Action (what you actually built) → Result (measurable outcome)." },
    metaKeywords: ["tcs ninja interview", "tcs digital interview", "tcs fresher interview", "tcs technical interview", "tcs interview questions 2026"],
    sitemapPriority: 0.95,
  },
  {
    slug: "tcs-hr-round-questions",
    searchPhrase: "TCS HR Round Interview Questions",
    company: "tcs", roleFamily: "behavioral", focus: "hr",
    intro: "TCS HR rounds are formal, process-oriented, and predictable. The interviewer follows a script — relocation willingness, salary expectations, why TCS over peers, 5-year goals. Authenticity beats memorised answers; be specific about why you're choosing TCS.",
    framework: { name: "PAR for HR", summary: "Problem (their question's underlying concern) → Answer (your direct response) → Reassurance (why you're not a flight risk)." },
    metaKeywords: ["tcs hr interview", "tcs hr round", "tcs hr questions", "tcs interview hr"],
    sitemapPriority: 0.85,
  },

  /* ── Infosys ───────────────────────────────────────────────── */
  {
    slug: "infosys-campus-interview-questions",
    searchPhrase: "Infosys Campus Interview Questions for Freshers",
    company: "infosys", roleFamily: "behavioral", focus: "campus-placement",
    intro: "Infosys campus rounds dwell on the academic project — 5-6 follow-ups on architecture, your specific contribution, and design trade-offs. The interviewer will ask 'why did you choose React over Angular?' even if your team made the call collectively. Have a real reason ready.",
    framework: { name: "Project storytelling", summary: "Context (what + why) → Your contribution (specific tasks) → Trade-offs (what you considered but didn't pick) → Outcome (measurable impact)." },
    metaKeywords: ["infosys campus interview", "infosys fresher interview", "infosys interview questions", "infosys placement"],
    sitemapPriority: 0.9,
  },

  /* ── Google ────────────────────────────────────────────────── */
  {
    slug: "google-india-engineering-interview-questions",
    searchPhrase: "Google India Engineering Interview Questions",
    company: "google", roleFamily: "swe", focus: "system-design",
    intro: "Google's SWE rounds prize first-principles thinking and explicit trade-off articulation. Always discuss what you're approximating. The bar-raiser will probe your assumptions with 'what if X were 100x larger?' — your answer reveals depth or its absence.",
    framework: { name: "First-principles design", summary: "What's the actual constraint? → Without prior solutions, what's the simplest correct approach? → Trade-offs at scale → Approximations that matter." },
    metaKeywords: ["google india interview", "google sde interview", "google engineering interview", "google system design"],
    sitemapPriority: 0.85,
  },
  {
    slug: "google-pm-interview-questions",
    searchPhrase: "Google Product Manager Interview Questions",
    company: "google", roleFamily: "pm", focus: "case-study",
    intro: "Google PM interviews favour candidates who decompose ambiguity quickly and don't get attached to their first answer. India-specific products (YouTube, GPay, Search-in-India) come up — know the local nuances vs the global product.",
    framework: { name: "PM CIRCLES", summary: "Comprehend the problem → Identify the user → Report their needs → Cut by impact → List solutions → Evaluate → Summarise." },
    metaKeywords: ["google pm interview", "google product manager", "google case study"],
    sitemapPriority: 0.85,
  },

  /* ── Amazon ────────────────────────────────────────────────── */
  {
    slug: "amazon-leadership-principles-interview",
    searchPhrase: "Amazon Leadership Principles Interview Questions",
    company: "amazon", roleFamily: "behavioral", focus: "behavioral",
    intro: "Amazon rounds map every behavioural answer to one of the 16 Leadership Principles. Be explicit about which principle your story illustrates — 'this is a Customer Obsession story because…' Bar-raisers reward this signposting.",
    framework: { name: "STAR + LP signposting", summary: "Pick the LP → Situation that highlights it → Task → Action (your specific behaviour, not the team's) → Result (data) → Brief reflection on what you'd do differently." },
    metaKeywords: ["amazon leadership principles", "amazon behavioral interview", "amazon star interview", "amazon lp interview"],
    sitemapPriority: 0.9,
  },
  {
    slug: "amazon-system-design-interview-questions",
    searchPhrase: "Amazon System Design Interview Questions",
    company: "amazon", roleFamily: "swe", focus: "system-design",
    intro: "Amazon SDE-2/3 system design rounds lean operational — design Prime's recommendation engine, the order-fulfilment pipeline, or a scale-resilient cart. Bar-raiser will probe failure modes aggressively. Be ready for 'what happens if this region goes down?'",
    framework: { name: "Operational design", summary: "Functional requirements → non-functional (latency, availability) → API contracts → data model → component diagram → failure modes + recovery." },
    metaKeywords: ["amazon system design", "amazon sde interview", "amazon technical interview"],
    sitemapPriority: 0.85,
  },

  /* ── Salary negotiation ─────────────────────────────────────── */
  {
    slug: "salary-negotiation-india-tech",
    searchPhrase: "Salary Negotiation Practice for Indian Tech Roles",
    company: "razorpay", focus: "salary-negotiation",
    intro: "Salary negotiation is a multi-phase conversation, not a one-shot ask. Indian tech rounds open with a soft anchor ('this is competitive for your level'), then test whether you push back with structure or just accept. Naming a specific number — anchoring first — correlates with higher final offers.",
    framework: { name: "BATNA-first negotiation", summary: "Know your walk-away → anchor first with a specific number → cite market data → tier the package (base / variable / equity / signing / benefits) → never accept on the first call." },
    metaKeywords: ["salary negotiation india", "salary negotiation tech", "ctc negotiation india", "indian tech salary negotiation"],
    sitemapPriority: 0.9,
  },

  /* ── Wipro ─────────────────────────────────────────────────────────── */
  {
    slug: "wipro-freshers-interview-questions",
    searchPhrase: "Wipro Interview Questions for Freshers 2026",
    company: "wipro", roleFamily: "campus", focus: "campus-placement",
    intro: "Wipro's fresher hiring runs through two tracks: Elite NTH (₹3.5 LPA) for general engineering and Turbo (₹6.5 LPA) for strong coders. The online test is the main filter — around 70% of candidates don't make it past the aptitude section. Know your data structures, master a readable coding style, and prepare every HR answer from the 'relocation is fine' baseline.",
    framework: { name: "APH for campus", summary: "Aptitude (score above 65%) → Project depth (defend every trade-off) → HR yes-set (relocation, shifts, bond) → specific Wipro reason." },
    metaKeywords: ["wipro interview questions freshers", "wipro elite nth", "wipro campus placement", "wipro interview preparation 2026"],
    sitemapPriority: 0.9,
    recruitmentSteps: [
      "Online Application via Wipro WILP portal or campus TnP cell",
      "Aptitude Test — Quantitative, Verbal, Logical + Written Communication",
      "Coding Round — 2 problems in 60 minutes (Turbo track: 3 hard problems)",
      "Technical Interview — CS fundamentals, project walkthrough",
      "HR Interview — Relocation, shift flexibility, expected CTC, bond acceptance",
    ],
    interviewRounds: [
      "Online Assessment (60–90 min): Aptitude + coding is the biggest filter. Solve at least 1 problem completely.",
      "Technical Round (45 min): OOP, SQL, OS basics, 1–2 simple DSA problems, and a deep project walkthrough.",
      "HR Round (20–30 min): Relocation + shift flexibility are non-negotiable at Wipro. Salary discussion, joining timeline.",
    ],
  },
  {
    slug: "wipro-turbo-technical-interview",
    searchPhrase: "Wipro Turbo Technical Interview Questions",
    company: "wipro", roleFamily: "swe", focus: "technical",
    intro: "Wipro Turbo (₹6.5 LPA) has a harder coding bar than Elite NTH. Expect 3 medium–hard DSA problems in the additional coding round — graph algorithms, DP, and sliding window are frequent. The technical interview that follows probes CS fundamentals aggressively and expects clean, commented code even in a competitive setting.",
    framework: { name: "DRACO for DSA", summary: "Define constraints → Recognise pattern → Approach out loud → Code cleanly → Optimise time/space → Complexity proof." },
    metaKeywords: ["wipro turbo interview", "wipro turbo technical round", "wipro turbo preparation", "wipro 6.5 lpa track"],
    sitemapPriority: 0.8,
  },

  /* ── HCL ───────────────────────────────────────────────────────────── */
  {
    slug: "hcl-freshers-interview-questions",
    searchPhrase: "HCL Interview Questions for Freshers 2026",
    company: "hcl", roleFamily: "campus", focus: "campus-placement",
    intro: "HCL Technologies hires 10,000+ freshers annually across its TechBee and Graduate Engineer Trainee programmes. The selection is two-stage: an online test heavy on reasoning + pseudo-code, followed by a single technical + HR combo interview. HCL specifically probes communication skills — this is a client-facing IT firm. Articulate answers score better than technically correct but unclear ones.",
    framework: { name: "CAP for fresher IT", summary: "Clarity first (explain concepts in plain English) → Application (link every concept to a use case) → Proof (one code snippet or formula to verify)." },
    metaKeywords: ["hcl freshers interview", "hcl get interview questions", "hcl campus placement 2026", "hcl techbee interview"],
    sitemapPriority: 0.85,
    recruitmentSteps: [
      "Online Registration at HCL Careers or campus TnP cell",
      "Online Assessment — Aptitude, Logical Reasoning, Verbal, Pseudo Code",
      "Technical + HR Interview (usually combined, 45–60 min)",
      "Document Verification + Background Check",
      "Offer Letter",
    ],
    interviewRounds: [
      "Online Test (60 min): Focus on pseudo-code section — it has the highest selection differential.",
      "Technical + HR Combo (45 min): CS fundamentals, 1–2 coding questions, final year project, relocation and CTC discussion.",
    ],
  },

  /* ── Cognizant ─────────────────────────────────────────────────────── */
  {
    slug: "cognizant-genc-interview-questions",
    searchPhrase: "Cognizant GenC Interview Questions for Freshers",
    company: "cognizant", roleFamily: "campus", focus: "campus-placement",
    intro: "Cognizant runs the largest fresher hiring programme in India through GenC (₹4 LPA) and GenC Pro (₹6.5 LPA). The CoCubes-proctored online test is strict on time — most candidates fail due to pacing, not knowledge. GenC Pro requires a separate coding round with 2 medium-level problems. Both tracks include a structured HR interview that screens for communication fit, not just skills.",
    framework: { name: "TIME for aptitude", summary: "Tough questions → skip for now. Identify easy ones first → Mark for review → Execute with exact formulas → return to skipped." },
    metaKeywords: ["cognizant genc interview", "cognizant fresher interview", "cognizant campus placement 2026", "cognizant genc pro"],
    sitemapPriority: 0.9,
    recruitmentSteps: [
      "Apply via campus TnP or Cognizant Careers portal",
      "Online Assessment (CoCubes) — Aptitude, Reasoning, English, Coding",
      "GenC Pro additional coding round (2 medium problems, 60 min)",
      "Technical Interview — CS fundamentals, project Q&A",
      "HR Interview — Behavioral, relocation, joining timeline",
    ],
    interviewRounds: [
      "Aptitude Test: Time-management is the differentiator — skip and return to hard questions.",
      "Coding Round (GenC Pro only): 2 medium DSA problems. Must fully solve at least 1.",
      "Technical Interview: OOP pillars, DBMS normalisation, one coding problem, project deep-dive.",
      "HR Interview: Why Cognizant, relocation, shift readiness, salary expectations.",
    ],
  },
  {
    slug: "cognizant-technical-interview-questions",
    searchPhrase: "Cognizant Technical Interview Questions 2026",
    company: "cognizant", roleFamily: "swe", focus: "technical",
    intro: "Cognizant technical interviews for experienced hires differ sharply from their campus rounds. The panel expects production-grade thinking — SOLID principles, REST API design, and real answers about deployment pipelines. 'I used it but don't know why' is a red flag. Come ready to explain every tool in your resume at the component level.",
    framework: { name: "SOLID + Deploy", summary: "SOLID design principles → REST contract → Database choice rationale → Deployment/CI pipeline → observability." },
    metaKeywords: ["cognizant technical interview", "cognizant sde interview", "cognizant interview questions 2026"],
    sitemapPriority: 0.75,
  },

  /* ── Accenture ─────────────────────────────────────────────────────── */
  {
    slug: "accenture-ase-interview-questions",
    searchPhrase: "Accenture ASE Interview Questions for Freshers",
    company: "accenture", roleFamily: "campus", focus: "campus-placement",
    intro: "Accenture's Associate Software Engineer programme is one of the most-applied-to fresher tracks in India. The iCAT online test filters on basic coding and aptitude, while the interview focuses heavily on communication and attitude fit. Accenture explicitly values 'client-ready' presentation — unclear or mumbled answers hurt more here than at product companies.",
    framework: { name: "CLIENT framework", summary: "Clarity (no jargon) → Leadership mindset → Initiative examples → Enthusiasm for the role → No-gap reasoning → Teamwork story." },
    metaKeywords: ["accenture ase interview", "accenture fresher interview", "accenture icat test", "accenture campus placement 2026"],
    sitemapPriority: 0.9,
    recruitmentSteps: [
      "Online Registration + resume submission",
      "iCAT Online Test — Cognitive Ability, Technical Competency, Coding (Java/Python/C++)",
      "Technical Interview — CS fundamentals, 1 coding problem, project walkthrough",
      "HR Interview — Communication assessment, values alignment, relocation",
      "Document Verification → Offer",
    ],
    interviewRounds: [
      "iCAT Test: Cognitive ability + 2 coding problems. At least 1 must fully run.",
      "Technical Interview (45 min): OOP, DBMS, OS, networking basics, project Q&A.",
      "HR Interview (30 min): Communication quality matters as much as content. Practice clear diction.",
    ],
  },
  {
    slug: "accenture-behavioral-interview-questions",
    searchPhrase: "Accenture Behavioral Interview Questions",
    company: "accenture", roleFamily: "behavioral", focus: "behavioral",
    intro: "Accenture's behavioral rounds for experienced hires probe client-management competencies more than technical depth. Expect questions about stakeholder conflict, scope creep, and timeline pressure — scenarios drawn directly from consulting and IT delivery. Stories where you calmed a difficult client or recovered a delayed project resonate most.",
    framework: { name: "CAR for consulting behavior", summary: "Context (client/delivery situation) → Action (your specific intervention, not the team's) → Result (deliverable shipped, escalation avoided, relationship preserved)." },
    metaKeywords: ["accenture behavioral interview", "accenture interview questions", "accenture values interview"],
    sitemapPriority: 0.75,
  },

  /* ── Capgemini ─────────────────────────────────────────────────────── */
  {
    slug: "capgemini-freshers-interview-questions",
    searchPhrase: "Capgemini Interview Questions for Freshers 2026",
    company: "capgemini", roleFamily: "campus", focus: "campus-placement",
    intro: "Capgemini's fresher hiring (Analyst, ₹4.35 LPA) runs on a two-section online test: IntelliAdapt (adaptive aptitude) and a programming test. The adaptive section adjusts difficulty in real time — answering correctly raises the bar; wrong answers lower it. The result is a capability score that determines shortlisting. The HR interview screens for communication, geography flexibility, and technology openness.",
    framework: { name: "Adaptive pacing", summary: "Answer what you know confidently → don't rush when questions get harder (that's a good sign) → skip-flag-return → keep calm on impossible questions (they calibrate the ceiling, not your failure)." },
    metaKeywords: ["capgemini interview questions freshers", "capgemini analyst interview", "capgemini campus 2026", "capgemini intelliadapt test"],
    sitemapPriority: 0.85,
    recruitmentSteps: [
      "Online Registration via Capgemini or campus TnP",
      "IntelliAdapt Test — Adaptive Aptitude + Programming test",
      "Technical Interview — CS fundamentals, coding problem",
      "HR Interview — Behavioral, relocation, technology preference",
    ],
    interviewRounds: [
      "IntelliAdapt Assessment: The difficulty adapts to your responses — harder questions mean you're doing well.",
      "Programming Test: 2 coding problems (easy–medium) in Java, Python, or C++.",
      "Technical Interview (30–40 min): OOPS, SQL, OS, networking basics, project discussion.",
      "HR Interview (20 min): Communication, relocation flexibility, salary expectation, joining date.",
    ],
  },

  /* ── LTIMindtree ───────────────────────────────────────────────────── */
  {
    slug: "ltimindtree-freshers-interview-questions",
    searchPhrase: "LTIMindtree Interview Questions for Freshers 2026",
    company: "ltimindtree", roleFamily: "campus", focus: "campus-placement",
    intro: "LTIMindtree (post-merger of LTI and Mindtree) has unified its fresher hiring with a strong emphasis on coding ability. The online assessment is harder than TCS/Wipro — expect 3 coding problems of increasing difficulty rather than 2 easy ones. LTIMindtree specifically looks for engineers who can write production-grade code, not just pseudocode.",
    framework: { name: "Code quality focus", summary: "Correct first → readable variable names → edge case handling → time-complexity comment → test mentally before submitting." },
    metaKeywords: ["ltimindtree interview questions freshers", "ltimindtree campus placement 2026", "lti mindtree interview"],
    sitemapPriority: 0.85,
    recruitmentSteps: [
      "Online Assessment — Aptitude + 3 Coding Problems",
      "Technical Interview — DSA, CS fundamentals, project walkthrough",
      "HR Interview — Relocation, bond terms, salary discussion",
    ],
    interviewRounds: [
      "Online Assessment: 3 coding problems. The 3rd is hard — solving 2 fully is the target.",
      "Technical Interview: Stronger DSA probing than TCS/Infosys. Expect graph or DP follow-ups.",
      "HR Interview: Standard relocation + flexibility screening. Mention specific LTIMindtree domain expertise (BFSI, insurance, retail).",
    ],
  },

  /* ── IBM ───────────────────────────────────────────────────────────── */
  {
    slug: "ibm-freshers-interview-questions",
    searchPhrase: "IBM Interview Questions for Freshers 2026",
    company: "ibm", roleFamily: "campus", focus: "campus-placement",
    intro: "IBM's fresher hiring (Application Developer, ₹4.5–6.5 LPA) focuses more on problem-solving attitude than raw coding speed. The interview has a strong written/verbal communication section, and IBM specifically asks about 'curiosity and continuous learning' — their cultural cornerstone. An IBM Badge, AWS, or any self-learning certification instantly differentiates you.",
    framework: { name: "THINK for IBM", summary: "Thoughtful problem breakdown → Human impact of solution → Inclusion of edge cases → New learning demonstrated → Knowledge of IBM services." },
    metaKeywords: ["ibm freshers interview", "ibm application developer interview", "ibm campus placement 2026"],
    sitemapPriority: 0.8,
    recruitmentSteps: [
      "Online Application + academic filter (typically 65%+)",
      "Cognitive Ability + Technical Assessment",
      "Technical Interview — Coding problem, CS fundamentals",
      "HR Interview — Cultural fit, IBM values, learning mindset",
    ],
    interviewRounds: [
      "Cognitive + Technical Test: Aptitude + 1–2 coding problems (Python or Java preferred).",
      "Technical Interview: Cloud basics (AWS/Azure/IBM Cloud), OOP, databases, your strongest project.",
      "HR Interview: Curiosity and continuous learning are IBM's core values — have a story ready.",
    ],
  },

  /* ── Deloitte ──────────────────────────────────────────────────────── */
  {
    slug: "deloitte-analyst-interview-questions",
    searchPhrase: "Deloitte Analyst Interview Questions India",
    company: "deloitte", roleFamily: "behavioral", focus: "behavioral",
    intro: "Deloitte's analyst interviews (USI, Advisory, Technology) are structured competency assessments. Each question maps to one of Deloitte's PACE principles (Purpose, Aspiration, Commitment, Excellence). The partner or manager interviewing you has a scorecard. Stories with clear professional impact, stakeholder complexity, and personal ownership score highest.",
    framework: { name: "PACE stories", summary: "Purpose (why the work mattered) → Aspiration (the target you set for yourself, not just the team) → Commitment (how you stayed engaged when hard) → Excellence (the measurable result)." },
    metaKeywords: ["deloitte analyst interview india", "deloitte interview questions", "deloitte ustech interview", "deloitte consulting india"],
    sitemapPriority: 0.85,
    recruitmentSteps: [
      "Application via Deloitte campus or direct portal",
      "Online Aptitude + Personality Assessment",
      "Group Discussion (some tracks)",
      "Panel Interview — Competency-based + technical",
      "HR Discussion — Compensation, joining, practice area",
    ],
    interviewRounds: [
      "Online Assessment: Aptitude + situational judgment. The situational section tests Deloitte values alignment.",
      "Panel Interview: Competency-based behavioral questions (STAR). May include a case component for advisory roles.",
      "HR Discussion: Practice area preference, location, expected CTC, start date.",
    ],
  },
  {
    slug: "deloitte-consulting-case-interview",
    searchPhrase: "Deloitte Consulting Case Interview Practice",
    company: "deloitte", roleFamily: "consultant", focus: "case-study",
    intro: "Deloitte consulting cases lean on operations and digital transformation more than pure strategy. Expect government/public sector clients, IT transformation scenarios, and turnaround situations. Candidates who demonstrate prior exposure to programme management, cost reduction, or digital rollouts land best with Deloitte panels.",
    framework: { name: "OD-Consult", summary: "Objective clarity → Diagnosis (current-state gap) → Levers (controllable vs. structural) → Trade-off matrix → Phased delivery plan → Risk flagging." },
    metaKeywords: ["deloitte consulting case interview", "deloitte case study", "deloitte strategy interview india"],
    sitemapPriority: 0.8,
  },

  /* ── McKinsey / BCG ────────────────────────────────────────────────── */
  {
    slug: "mckinsey-case-study-interview-questions",
    searchPhrase: "McKinsey Case Study Interview Questions India",
    company: "mckinsey", roleFamily: "consultant", focus: "case-study",
    intro: "McKinsey India cases are unstructured by design. The interviewer deliberately withholds information to see how you ask for it. Every case can shift direction mid-way. The bar is hypothesis-first thinking: state what you believe the answer is before proving it, then adjust with evidence. Structured but rigid frameworks fail here.",
    framework: { name: "Hypothesis-first", summary: "State your hypothesis in the first 30 seconds → structure the proof → eliminate branches quickly with data questions → update hypothesis → synthesise before time." },
    metaKeywords: ["mckinsey case interview india", "mckinsey interview questions", "mckinsey pei india", "mckinsey india consulting interview"],
    sitemapPriority: 0.85,
  },
  {
    slug: "bcg-case-interview-practice",
    searchPhrase: "BCG Case Interview Practice Questions India",
    company: "bcg", roleFamily: "consultant", focus: "case-study",
    intro: "BCG interviews alternate between a candidate-led case and a BCG-led case in the same loop. The candidate-led case tests whether you can drive structure without prompts. BCG is known for market-sizing and profitability diagnoses with ambiguous data — the right answer is always 'it depends, and here is my framework for deciding.'",
    framework: { name: "BCG 3C", summary: "Client's core objective → Context (industry, constraints, data gaps) → Creative synthesis (non-obvious recommendation with quantified upside)." },
    metaKeywords: ["bcg case interview india", "bcg interview questions", "bcg consulting india", "bcg case study practice"],
    sitemapPriority: 0.8,
  },

  /* ── Goldman Sachs / JPMorgan ──────────────────────────────────────── */
  {
    slug: "goldman-sachs-interview-questions-india",
    searchPhrase: "Goldman Sachs Interview Questions India",
    company: "goldman", roleFamily: "finance", focus: "behavioral",
    intro: "Goldman Sachs interviews in India (Bengaluru, Hyderabad) span engineering and finance. SDE interviews are structurally similar to FAANG — DSA + system design — but with an extra emphasis on financial domain awareness. Finance analyst interviews require DCF fluency and the ability to articulate why a specific market move happened in the last week.",
    framework: { name: "Domain + Code", summary: "Financial domain awareness (what does a settlement system do) → DSA pattern recognition → System reliability (idempotency, exactly-once delivery) → Communication under pressure." },
    metaKeywords: ["goldman sachs interview india", "goldman sachs sde interview", "goldman sachs analyst interview india"],
    sitemapPriority: 0.8,
  },
  {
    slug: "jpmorgan-interview-questions-india",
    searchPhrase: "JPMorgan Interview Questions for India Roles",
    company: "jpmc", roleFamily: "finance", focus: "behavioral",
    intro: "JPMorgan's India engineering and analyst interviews have a strong compliance and regulatory awareness thread. Candidates are expected to understand why financial systems must be auditable, idempotent, and aligned with RBI/SEBI regulations. Combining technical depth with awareness of financial regulation instantly separates candidates at JPMorgan.",
    framework: { name: "AUDIT + SCALE", summary: "Audit trail (every mutation is loggable) → Uptime (99.99% SLA) → Data integrity → Idempotency → Trade reconciliation → Scale estimation." },
    metaKeywords: ["jpmorgan interview india", "jp morgan sde interview india", "jpmc analyst interview"],
    sitemapPriority: 0.8,
  },

  /* ── CRED ──────────────────────────────────────────────────────────── */
  {
    slug: "cred-engineering-interview-questions",
    searchPhrase: "CRED Engineering Interview Questions",
    company: "cred", roleFamily: "swe", focus: "system-design",
    intro: "CRED engineering rounds are among the hardest in India. Expect a take-home assignment followed by a 4–5 round loop probing system design, low-level design, and distributed systems. CRED engineers work on credit-card reward pipelines, gamification engines, and real-time financial data at scale — idempotency, ledger consistency, and point-accrual systems are common themes.",
    framework: { name: "Financial reliability", summary: "Ledger double-entry (debits = credits) → Idempotency keys for all mutations → Event sourcing for auditability → Compensating transactions on failure → p99 latency budget." },
    metaKeywords: ["cred engineering interview", "cred sde interview", "cred system design interview", "cred technical interview"],
    sitemapPriority: 0.85,
    interviewRounds: [
      "Take-Home Assignment: A small full-stack or backend problem evaluated on code quality, not speed.",
      "Low-Level Design (60 min): Design a class system (parking lot, reward engine, inventory). Clean OOP expected.",
      "System Design (60 min): CRED-flavoured — design a credit-card rewards pipeline or payment notification system.",
      "DSA / Problem Solving (60 min): Medium–hard Leetcode, sometimes 2 problems back-to-back.",
      "Hiring Manager + Culture (45 min): Ownership stories, past system failures, what you'd build at CRED.",
    ],
  },
  {
    slug: "cred-pm-interview-questions",
    searchPhrase: "CRED Product Manager Interview Questions",
    company: "cred", roleFamily: "pm", focus: "case-study",
    intro: "CRED PM interviews are deceptively philosophical. Questions often start with 'What does trust mean in a financial product?' or 'How do you design for a premium user who doesn't need to be incentivised?' The product team obsesses over micro-interactions. Cases will test taste as much as market sizing.",
    framework: { name: "Premium product lens", summary: "User trust foundation → friction removal over feature addition → signal quality over quantity → premium cohort behaviour → qualitative research over A/B tests." },
    metaKeywords: ["cred pm interview", "cred product manager interview", "cred fintech product interview"],
    sitemapPriority: 0.8,
  },

  /* ── Meesho ────────────────────────────────────────────────────────── */
  {
    slug: "meesho-engineering-interview-questions",
    searchPhrase: "Meesho Engineering Interview Questions",
    company: "meesho", roleFamily: "swe", focus: "system-design",
    intro: "Meesho engineering interviews blend social commerce with supply-chain scale. Their system design questions often model real Meesho infrastructure — catalog search for 150M SKUs, seller-payout settlement, or return-logistics orchestration across tier-3 PIN codes. They expect product awareness alongside system design depth.",
    framework: { name: "Commerce + Logistics", summary: "Write path vs. read path separation → Catalog sharding strategy → Eventual consistency in inventory → COD return flow idempotency → Seller payout reconciliation." },
    metaKeywords: ["meesho engineering interview", "meesho sde interview", "meesho system design", "meesho technical interview"],
    sitemapPriority: 0.8,
    interviewRounds: [
      "Online Assessment: 2–3 DSA problems. Medium–hard level.",
      "DSA Round (60 min): Graphs, DP, string manipulation — one hard problem with optimisation follow-up.",
      "System Design (60 min): Social commerce or logistics system. Ask about scale and COD specifics early.",
      "Behavioral + Manager (45 min): Ownership, speed, first-principles thinking. Meesho values speed over perfection.",
    ],
  },
  {
    slug: "meesho-pm-interview-questions",
    searchPhrase: "Meesho Product Manager Interview Questions",
    company: "meesho", roleFamily: "pm", focus: "case-study",
    intro: "Meesho PM interviews focus on tier-2/3 India constraints that urban-educated candidates often miss. Their typical question: 'Design for a seller who uses a feature-phone, has a 2G connection, and speaks only Kannada.' Empathy with non-English, low-bandwidth, first-time-online users is a differentiator. Cases reward simplification and distribution strategy over sophisticated UX.",
    framework: { name: "Bharat-first PM", summary: "Language + connectivity constraints first → literacy level (visual over text) → trust signals for first transactions → distribution via WhatsApp/share chain → reseller economics." },
    metaKeywords: ["meesho pm interview", "meesho product manager interview", "meesho case study interview"],
    sitemapPriority: 0.75,
  },

  /* ── Swiggy (engineering) ──────────────────────────────────────────── */
  {
    slug: "swiggy-engineering-interview-questions",
    searchPhrase: "Swiggy Engineering Interview Questions",
    company: "swiggy", roleFamily: "swe", focus: "system-design",
    intro: "Swiggy's engineering interviews probe real-time logistics systems under adversarial conditions — monsoon zone outages, restaurant denial cascades, surge demand from cricket finals. The system design bar is high and operationally specific: how do you ensure a delivery-partner notification reaches them in under 200ms when 5000 orders are simultaneously dispatched?",
    framework: { name: "Logistics reliability", summary: "Geospatial indexing strategy → push vs. pull notification → demand prediction model → rebalancing algorithm → fallback path → delivery SLA breach escalation." },
    metaKeywords: ["swiggy engineering interview", "swiggy sde interview", "swiggy system design", "swiggy technical interview"],
    sitemapPriority: 0.8,
  },

  /* ── Zerodha ───────────────────────────────────────────────────────── */
  {
    slug: "zerodha-engineering-interview-questions",
    searchPhrase: "Zerodha Engineering Interview Questions",
    company: "zerodha", roleFamily: "swe", focus: "technical",
    intro: "Zerodha engineering interviews are distinctly different from startup norms. No Leetcode marathons — instead, they give you a real Kite (trading platform) problem and ask you to reason about it. They expect deep curiosity about financial markets alongside engineering. Know order types, margin calculations, and SEBI circuit breaker rules. Passion for markets is evaluated, not just code quality.",
    framework: { name: "Markets + Engineering", summary: "Order matching logic → margin risk exposure → real-time P&L computation → regulatory compliance hooks → system fail-safe on circuit break events." },
    metaKeywords: ["zerodha interview questions", "zerodha engineering interview", "zerodha sde interview", "zerodha kite technical"],
    sitemapPriority: 0.8,
  },

  /* ── Freshworks ────────────────────────────────────────────────────── */
  {
    slug: "freshworks-sde-interview-questions",
    searchPhrase: "Freshworks Software Engineer Interview Questions",
    company: "freshworks", roleFamily: "swe", focus: "system-design",
    intro: "Freshworks SDE interviews have a customer-success flavour that surprises candidates from purely product-company backgrounds. Interviewers explicitly ask: 'How would you explain this architecture decision to a non-technical customer success manager?' The engineering bar is solid — medium-hard DSA + distributed systems — but product empathy is equally weighted.",
    framework: { name: "SaaS reliability", summary: "Multi-tenant data isolation → webhook delivery guarantees → customer-facing API stability → SLA monitoring → graceful degradation on 3rd-party API failures." },
    metaKeywords: ["freshworks interview questions", "freshworks sde interview", "freshworks system design", "freshworks engineering interview"],
    sitemapPriority: 0.8,
  },
  {
    slug: "freshworks-pm-interview-questions",
    searchPhrase: "Freshworks Product Manager Interview Questions",
    company: "freshworks", roleFamily: "pm", focus: "case-study",
    intro: "Freshworks PM interviews start with an unusual premise: the user is the support agent, not the customer. Their PM cases ask you to design for operational efficiency — reducing average handle time, automating ticket routing, improving agent sentiment. Cases favour candidates who understand the B2B SaaS buying journey.",
    framework: { name: "B2B SaaS PM", summary: "Define the agent/operator persona → identify friction in their workflow → prioritise by time-saved per agent × agent count → build-vs-integrate decision → success metric (AHT reduction, CSAT lift)." },
    metaKeywords: ["freshworks pm interview", "freshworks product manager interview", "freshworks case study"],
    sitemapPriority: 0.75,
  },

  /* ── Microsoft ─────────────────────────────────────────────────────── */
  {
    slug: "microsoft-india-sde-interview-questions",
    searchPhrase: "Microsoft India SDE Interview Questions",
    company: "microsoft", roleFamily: "swe", focus: "system-design",
    intro: "Microsoft India SDE interviews (Hyderabad, Bangalore) follow the global Microsoft loop: 4–5 rounds of DSA + one system design + a behavioral round. Microsoft has a high bar on code quality — interviewers expect readable, commented code and a discussion of testing strategy. The system design round often involves Azure services; knowing Azure vs. AWS trade-offs is a differentiator.",
    framework: { name: "Azure-aware design", summary: "Functional requirements → Azure service selection rationale → data store choice → message bus (Service Bus vs Event Hub) → monitoring + alerting → cost at scale." },
    metaKeywords: ["microsoft india sde interview", "microsoft hyderabad interview", "microsoft technical interview india", "microsoft azure system design"],
    sitemapPriority: 0.9,
    recruitmentSteps: [
      "Online Assessment — Coding problems (HackerRank) + MCQ",
      "Phone Screen with Recruiter",
      "4–5 Onsite/Virtual Rounds: DSA (×2–3) + System Design (×1) + Behavioral (×1)",
      "Hiring Committee Review",
      "Offer + Azure team matching",
    ],
    interviewRounds: [
      "Online Assessment: 3 medium coding problems. Passing bar is 2 fully solved.",
      "DSA Rounds (×2–3): Medium–hard problems. Expect follow-ups on time/space optimisation.",
      "System Design (1 hr): Azure-flavoured. Mention Azure services specifically — it's a differentiator.",
      "Behavioral Round: Microsoft Growth Mindset is the cultural lens. Have a 'I was wrong and changed' story.",
    ],
  },
  {
    slug: "microsoft-pm-interview-questions",
    searchPhrase: "Microsoft Product Manager Interview Questions",
    company: "microsoft", roleFamily: "pm", focus: "case-study",
    intro: "Microsoft PM interviews are known for asking 'How would you improve [Microsoft product] for a specific market?' India-specific questions come up — Teams for rural education, Bing for Bharat, Office for SMBs with limited English. The Growth Mindset cultural lens means interviewers reward candidates who show they changed their mind based on evidence.",
    framework: { name: "Improve product loop", summary: "Define the user segment precisely → identify top unmet need with data → propose feature → define success metrics → call out risks + growth mindset moment." },
    metaKeywords: ["microsoft pm interview", "microsoft product manager interview", "microsoft program manager interview india"],
    sitemapPriority: 0.85,
  },
  {
    slug: "microsoft-behavioral-interview-questions",
    searchPhrase: "Microsoft Behavioral Interview Questions — Growth Mindset",
    company: "microsoft", roleFamily: "behavioral", focus: "behavioral",
    intro: "Microsoft's behavioral interviews are anchored in the Growth Mindset model. The most valued answer is one where you describe clearly updating your beliefs or behaviour based on evidence. 'I was right all along' stories are red flags. 'Here is what I learned I was wrong about' stories resonate strongly with Microsoft panels.",
    framework: { name: "Growth story", summary: "Initial belief or assumption → evidence that challenged it → specific change you made → outcome after the change → reflection on why you held the old belief." },
    metaKeywords: ["microsoft behavioral interview", "microsoft growth mindset interview", "microsoft interview questions india"],
    sitemapPriority: 0.8,
  },

  /* ── Meta ──────────────────────────────────────────────────────────── */
  {
    slug: "meta-engineering-interview-questions",
    searchPhrase: "Meta Engineering Interview Questions",
    company: "meta", roleFamily: "swe", focus: "system-design",
    intro: "Meta's SDE interviews are among the hardest in the industry. Coding rounds require speed — 2 medium-hard problems in 45 minutes, often graph or DP. System design rounds probe social graph architecture, content ranking algorithms, and ad delivery at planetary scale. The bar raiser culture means one interviewer can block an offer even if all others say yes.",
    framework: { name: "Social graph design", summary: "Feed generation algorithm → graph traversal at scale → ranking signal selection → write path vs read path → privacy partitioning → abuse signal integration." },
    metaKeywords: ["meta engineering interview", "meta sde interview", "meta system design interview", "facebook interview india"],
    sitemapPriority: 0.85,
    interviewRounds: [
      "Coding Screen (45 min): 2 medium–hard problems. Meta expects clean, well-commented code in 40 minutes.",
      "DSA Round 1 (45 min): Graphs or trees. Expect follow-up complexity questions.",
      "DSA Round 2 (45 min): DP or string manipulation. Must fully solve both.",
      "System Design (60 min): Social or ad-system design. Meta scale = 3B users. Size your system accordingly.",
      "Behavioral (45 min): Meta values — Move Fast, Be Bold, Be Open, Focus on Impact. Have stories mapped.",
    ],
  },
  {
    slug: "meta-behavioral-interview-questions",
    searchPhrase: "Meta Behavioral Interview Questions",
    company: "meta", roleFamily: "behavioral", focus: "behavioral",
    intro: "Meta's behavioral interviews map answers to their 5 core values: Move Fast, Be Bold, Be Open, Build Social Value, Focus on Impact. The interviewer tracks which value each story illustrates — be explicit. Meta specifically probes for candidates who moved quickly even with incomplete information and who disagree publicly but commit fully once a decision is made.",
    framework: { name: "Meta values map", summary: "Identify the Meta value → Situation (why it was high-stakes) → Your specific action → Impact (must be quantified or scoped) → explicit callout of which value it illustrates." },
    metaKeywords: ["meta behavioral interview", "meta values interview", "facebook behavioral interview india"],
    sitemapPriority: 0.8,
  },

  /* ── Netflix ───────────────────────────────────────────────────────── */
  {
    slug: "netflix-engineering-interview-questions",
    searchPhrase: "Netflix Engineering Interview Questions",
    company: "netflix", roleFamily: "swe", focus: "system-design",
    intro: "Netflix engineering interviews have a distinct culture fit layer: they pay exceptionally well and expect senior-level judgment from every engineer. Interviews probe not just technical skill but strategic thinking. Chaos engineering (Netflix Simian Army philosophy), microservice resilience, and global CDN strategies are recurring themes.",
    framework: { name: "Chaos-resilient design", summary: "Define failure blast radius → circuit breaker placement → graceful degradation paths → observability (distributed tracing) → runbook for on-call → chaos experiment design." },
    metaKeywords: ["netflix engineering interview", "netflix sde interview", "netflix system design interview"],
    sitemapPriority: 0.8,
  },

  /* ── Amazon PM ─────────────────────────────────────────────────────── */
  {
    slug: "amazon-pm-interview-questions",
    searchPhrase: "Amazon Product Manager Interview Questions India",
    company: "amazon", roleFamily: "pm", focus: "case-study",
    intro: "Amazon PM interviews (India: Bangalore, Hyderabad) are almost entirely behavioral, anchored to the 16 Leadership Principles — unlike most PM interviews that have case studies. 'Tell me about a time you launched a product that failed' and 'Describe a time you had to make a fast decision with insufficient data' are characteristic questions. Every answer must link explicitly to a Leadership Principle.",
    framework: { name: "LP-mapped PM story", summary: "Name the LP → Situation (product context) → Task (your specific PM responsibility) → Action (decisions you made, not the team) → Result (metric) → LP reinforcement." },
    metaKeywords: ["amazon pm interview india", "amazon product manager interview", "amazon apm interview india", "amazon lp pm interview"],
    sitemapPriority: 0.85,
  },

  /* ── Google (behavioral) ───────────────────────────────────────────── */
  {
    slug: "google-behavioral-interview-questions",
    searchPhrase: "Google Behavioral Interview Questions — Googleyness",
    company: "google", roleFamily: "behavioral", focus: "behavioral",
    intro: "Google's 'Googleyness' rounds test four things: cognitive bias awareness, comfort with ambiguity, collaborative problem-solving, and openness to being wrong. These aren't soft-skill fluff rounds — they carry equal weight to coding rounds in the hiring committee. Candidates who give polished, perfectly packaged STAR answers often score lower than those who show genuine reflection and self-awareness.",
    framework: { name: "Genuine reflection", summary: "Situation (specific, not abstract) → Your initial assumption → Point where you had to update the assumption → What changed → What you'd do differently." },
    metaKeywords: ["google behavioral interview", "googleyness interview", "google googliness questions", "google cultural interview"],
    sitemapPriority: 0.85,
  },

  /* ── LinkedIn ──────────────────────────────────────────────────────── */
  {
    slug: "linkedin-pm-interview-questions",
    searchPhrase: "LinkedIn Product Manager Interview Questions",
    company: "linkedin", roleFamily: "pm", focus: "case-study",
    intro: "LinkedIn PM interviews are unique because you're interviewing at the platform you used to get the interview. Interviewers will ask 'How would you improve LinkedIn Jobs?' or 'Design a feature for LinkedIn India's blue-collar workers.' Having a specific, data-backed opinion about LinkedIn's product shortcomings — and a constructive improvement — is the most memorable thing you can do.",
    framework: { name: "Platform insider", summary: "User segment (creators vs consumers vs job seekers) → current friction point (with example) → feature proposal → success metric (engagement + retention) → monetisation upside." },
    metaKeywords: ["linkedin pm interview", "linkedin product manager interview", "linkedin india interview"],
    sitemapPriority: 0.75,
  },

  /* ── Adobe ─────────────────────────────────────────────────────────── */
  {
    slug: "adobe-engineering-interview-questions",
    searchPhrase: "Adobe Engineering Interview Questions India",
    company: "adobe", roleFamily: "swe", focus: "system-design",
    intro: "Adobe India (Noida, Bangalore) interviews follow a structured 4-round loop: DSA, low-level design, system design, and behavioral. Adobe's system design questions often involve document collaboration (Acrobat, Sign, XD) or digital marketing data pipelines (Analytics, Campaign). Candidates who understand Adobe's product portfolio and can connect engineering choices to product constraints stand out.",
    framework: { name: "Document + Data design", summary: "Real-time collaboration (operational transforms or CRDT) → versioning and conflict resolution → multi-tenant data isolation → high-throughput event pipeline → access control granularity." },
    metaKeywords: ["adobe engineering interview india", "adobe sde interview", "adobe technical interview noida", "adobe system design"],
    sitemapPriority: 0.8,
    interviewRounds: [
      "DSA Round (60 min): Medium–hard problems. Graph or DP focus.",
      "Low-Level Design (60 min): Design a class system (document editor, calendar, booking system). OOP depth matters.",
      "System Design (60 min): Often document-collaboration or analytics pipeline themed.",
      "Behavioral (45 min): Adobe values creativity and customer obsession. Have a user-impact story ready.",
    ],
  },

  /* ── TCS (behavioral) ──────────────────────────────────────────────── */
  {
    slug: "tcs-behavioral-interview-questions",
    searchPhrase: "TCS Behavioral and Managerial Round Interview Questions",
    company: "tcs", roleFamily: "behavioral", focus: "behavioral",
    intro: "TCS's managerial round is the most misunderstood part of its hiring process. Candidates who cruise through the NQT often fail here because they answer generic questions generically. TCS interviewers specifically test: relocation willingness, team fit, conflict handling, and the 'why TCS over competitors' question — which must have a specific, non-generic answer.",
    framework: { name: "TCS-fit signalling", summary: "Process discipline story → team player example → clear relocation/shift yes → why TCS (cite specific initiative) → 5-year goal aligned with TCS growth areas." },
    metaKeywords: ["tcs behavioral interview", "tcs managerial round", "tcs mr round questions", "tcs interview mr"],
    sitemapPriority: 0.85,
  },

  /* ── Infosys (Power Programmer) ────────────────────────────────────── */
  {
    slug: "infosys-power-programmer-interview",
    searchPhrase: "Infosys Power Programmer Interview Questions",
    company: "infosys", roleFamily: "swe", focus: "technical",
    intro: "Infosys Power Programmer (₹6.5 LPA) is the hardest fresher track at Infosys. The coding round has 3 problems — you need to fully solve at least 2. The interview digs into data structures at depth: not 'what is a binary tree' but 'implement a self-balancing AVL tree and explain the rotation algorithm.' Candidates from competitive programming backgrounds dominate this track.",
    framework: { name: "CP-grade prep", summary: "Full complexity analysis (best, average, worst) → space optimisation trade-offs → alternative algorithms + why you chose this one → corner cases (empty input, MAX_INT, null pointers) → clean code under time pressure." },
    metaKeywords: ["infosys power programmer interview", "infosys pp track interview", "infosys 6.5 lpa interview", "infosys coding interview"],
    sitemapPriority: 0.85,
  },

  /* ── OYO ───────────────────────────────────────────────────────────── */
  {
    slug: "oyo-engineering-interview-questions",
    searchPhrase: "OYO Engineering Interview Questions",
    company: "oyo", roleFamily: "swe", focus: "system-design",
    intro: "OYO engineering interviews have evolved significantly post-restructuring. The bar is now rigorous — expect 3–4 rounds with a strong system design component focused on hotel booking, dynamic pricing, and property management systems. OYO interviewers specifically ask about designing for markets where properties go offline unexpectedly — graceful degradation matters here.",
    framework: { name: "Hospitality systems", summary: "Inventory availability in near-realtime → dynamic pricing algorithm → booking idempotency → property onboarding pipeline → partner reconciliation → cancellation policy engine." },
    metaKeywords: ["oyo engineering interview", "oyo sde interview", "oyo system design interview", "oyo technical interview"],
    sitemapPriority: 0.75,
  },

  {
    slug: "phonepe-behavioral-interview-questions",
    searchPhrase: "PhonePe Behavioral Interview Questions — Values and Culture Fit",
    company: "phonepe", roleFamily: "behavioral", focus: "behavioral",
    intro: "PhonePe's culture interviews probe a specific set of values: customer obsession, ownership over process, and speed-accuracy balance. They operate in a sector where bugs cost real money — so they specifically probe how you handle high-stakes decisions and production incidents. The behavioral round is eliminatory — PhonePe rejects technically strong candidates who don't demonstrate ownership mentality.",
    framework: { name: "Ownership-first STAR", summary: "Identify the moment you chose ownership over comfort → specific decision → measurable outcome → what you'd change → connection to PhonePe's mission." },
    metaKeywords: ["phonepe behavioral interview", "phonepe values interview", "phonepe culture fit", "phonepe hr round questions"],
    sitemapPriority: 0.8,
  },

  /* ── Amazon SWE behavioral (LP-focused) ────────────────────────────── */
  {
    slug: "amazon-sde-leadership-principles-interview",
    searchPhrase: "Amazon SDE Behavioral Interview — Leadership Principles",
    company: "amazon", roleFamily: "swe", focus: "behavioral",
    intro: "Amazon's behavioral rounds for SDE roles are as important as the coding rounds — candidates who nail all 4 DSA questions but fail the LP (Leadership Principles) interview don't get offers. Amazon uses structured STAR evaluation across all 16 LPs. The trick: you don't need one story per LP. You need 8–10 strong stories that each demonstrate 2–3 principles, and you adapt them to the question asked.",
    framework: { name: "LP story mapping", summary: "Identify your 8–10 strongest STAR stories → map each to 2–3 Leadership Principles → practice adapting the same story for different LP questions → flag the LP being tested in every answer." },
    metaKeywords: ["amazon sde behavioral interview", "amazon leadership principles interview india", "amazon lp questions sde", "amazon 2026 behavioral questions"],
    sitemapPriority: 0.9,
    interviewRounds: [
      "Phone Screen (45–60 min): 1–2 coding problems (easy-medium) + 1–2 LP questions.",
      "Virtual Onsite Round 1 — DSA: Hard problem with optimal-solution requirement.",
      "Virtual Onsite Round 2 — DSA: Medium-hard + problem extension / edge cases.",
      "Virtual Onsite Round 3 — System Design (SDE-2+): Design at Amazon's scale (millions of users, global distribution).",
      "Virtual Onsite Round 4 — Bar Raiser: Pure LP deep-dive. Expect pushback and follow-up on every answer.",
    ],
  },

  /* ── Amazon campus India ────────────────────────────────────────────── */
  {
    slug: "amazon-campus-placement-india",
    searchPhrase: "Amazon Campus Placement Interview Questions India Freshers",
    company: "amazon", roleFamily: "campus", focus: "campus-placement",
    intro: "Amazon's India campus hiring has grown significantly — they recruit from IITs, NITs, and top private colleges for SDE-1 roles. The campus process is more structured than lateral hiring but equally rigorous on DSA. Amazon campus interviews are notable for combining hard DSA with LP questions even at the fresher level — understanding why 'Ownership' and 'Deliver Results' apply to a college project is a specific preparation need.",
    framework: { name: "SDE-1 LP anchoring", summary: "Map college projects to LPs → quantify outcomes (users, lines of code, performance improvement) → practice the 'college project version' of each LP story → be ready to extend to production scale." },
    metaKeywords: ["amazon campus placement india", "amazon sde-1 interview freshers india", "amazon off-campus india 2026", "amazon fresher interview"],
    sitemapPriority: 0.88,
    recruitmentSteps: [
      "Apply via Amazon University Talent Acquisition portal or campus drive",
      "Online assessment: 2 coding problems + 20 debugging MCQs (90 min)",
      "Technical interview 1: DSA + 1–2 LP questions",
      "Technical interview 2: DSA + system-level thinking (no full system design for SDE-1)",
      "HR interview: LP-deep dive + compensation discussion",
    ],
  },

  /* ── IBM campus / consulting ────────────────────────────────────────── */
  {
    slug: "ibm-campus-placement-interview-questions",
    searchPhrase: "IBM Campus Placement Interview Questions India Freshers 2026",
    company: "ibm", roleFamily: "campus", focus: "campus-placement",
    intro: "IBM hires several thousand freshers in India annually across the GBS (Global Business Services) and GTS (Global Technology Services) tracks. The campus process is split: GBS has a case/consulting flavour; GTS is technical. The first filter is an IBM aptitude test (Cognitive Ability Assessment) that's harder than TCS but more predictable than Wipro NLTH. IBM's interview for freshers does not require competitive programming — but CS fundamentals at depth are essential.",
    framework: { name: "IBM values signalling", summary: "Service orientation story → teamwork over individual glory → client-impact metric → willingness to learn new tech → IBM Innovation story link (research, Watson, hybrid cloud)." },
    metaKeywords: ["ibm campus placement india", "ibm fresher interview 2026", "ibm cognitive ability test", "ibm gbs gts interview india"],
    sitemapPriority: 0.8,
    recruitmentSteps: [
      "Apply via IBM campus recruitment portal or participate in campus drive",
      "Cognitive Ability Assessment (online): Verbal, Numerical, Abstract reasoning",
      "Group Discussion — for GBS track only",
      "Technical Interview: CS fundamentals (OOP, DBMS, OS, Networking) + simple coding",
      "HR Interview: Values alignment, relocation, and career aspirations",
    ],
  },
  {
    slug: "ibm-consultant-interview-questions",
    searchPhrase: "IBM Consultant Interview Questions — GBS Strategy and Consulting",
    company: "ibm", roleFamily: "consultant", focus: "case-study",
    intro: "IBM GBS (Global Business Services) consulting interviews are case-forward but with a tech twist — IBM differentiates itself from pure-play consultancies by tying solutions to IBM's technology stack (hybrid cloud, AI/ML, SAP). Cases often involve digital transformation for large enterprises. Unlike McKinsey/BCG, IBM GBS cases lean toward 'how would you implement this technically' rather than 'should the client enter this market.'",
    framework: { name: "IBM consulting framework", summary: "Business problem → technology solution fit → change management → ROI model → phased implementation → client capability building." },
    metaKeywords: ["ibm gbs interview", "ibm consultant interview india", "ibm consulting case study", "ibm strategy consulting india"],
    sitemapPriority: 0.78,
  },

  /* ── Infosys behavioral ─────────────────────────────────────────────── */
  {
    slug: "infosys-behavioral-interview-questions",
    searchPhrase: "Infosys Behavioral and HR Interview Questions — InfyTQ Assessment",
    company: "infosys", roleFamily: "behavioral", focus: "behavioral",
    intro: "Infosys behavioral interviews have two distinct formats: the structured HR interview for fresh hires (focused on relocation, team-fit, strength/weakness) and the managerial round for experienced laterals (focused on stakeholder management and conflict resolution). Both are assessed on communication quality as much as content. The InfyTQ platform pre-qualifies many hires — candidates who clear it at high scores often get more in-depth behavioral rounds.",
    framework: { name: "Infosys cultural fit", summary: "Communication clarity → learning agility story → integrity under pressure example → client-centricity → relocation openness (explicitly required) → why Infosys over competitors." },
    metaKeywords: ["infosys behavioral interview", "infosys hr round questions", "infosys managerial round", "infosys interview tips 2026"],
    sitemapPriority: 0.82,
  },

  /* ── Wipro behavioral ───────────────────────────────────────────────── */
  {
    slug: "wipro-behavioral-interview-questions",
    searchPhrase: "Wipro Behavioral and HR Interview Questions — WILP and NLTH",
    company: "wipro", roleFamily: "behavioral", focus: "behavioral",
    intro: "Wipro's HR round is traditionally the easiest filter in their interview process — but candidates who underprep it do fail. The most common reason: vague answers to relocation and night-shift availability questions that have clear expected answers. Wipro's National Level Talent Hunt (NLTH) and TurboHire tracks also vary in behavioral depth. WILP hires get a more rigorous values interview.",
    framework: { name: "Wipro HR essentials", summary: "Relocation yes (be explicit) → night-shift availability yes → why Wipro (cite WILP/TurboHire/specific practice) → strength with work example → weakness with mitigation → 5-year goal aligned with IT services growth." },
    metaKeywords: ["wipro hr round questions", "wipro behavioral interview", "wipro interview tips", "wipro nlth interview 2026"],
    sitemapPriority: 0.8,
  },
];

/** Lookup helper. */
export function getSeoPageBySlug(slug: string): SeoPage | undefined {
  return SEO_PAGES.find((p) => p.slug === slug);
}

/** All slugs for static-params generation in Next.js. */
export function getAllSeoSlugs(): string[] {
  return SEO_PAGES.map((p) => p.slug);
}
