/**
 * Generate a markdown per-company changelog summarizing what the CSV
 * fallback adds and corrects vs the prior curator-only state.
 *
 *   npx tsx scripts/csv-changelog.mts > docs/csv-100-company-changelog.md
 */
import {
  CSV_COMPANY_ROLE_BANDS,
  type CsvLevel,
} from "../data/csv-company-role-bands";
import { COMPANY_SALARY_OVERRIDES } from "../data/company-salary-overrides";
import { COMPANY_NEGOTIATION_CONTEXT } from "../data/company-negotiation-context";
import { matchRoleKey } from "../data/salaries";

function normalizeKey(name: string): string {
  let k = name.toLowerCase().trim();
  k = k.replace(/[.,;:!?]+$/g, "").trim();
  if (k.endsWith(" india")) k = k.slice(0, -" india".length).trim();
  return k;
}
function csvLevelToExp(l: CsvLevel) {
  if (l === "fresher" || l === "junior") return "entry";
  if (l === "manager") return "executive";
  return l;
}

const out: string[] = [];
out.push("# 100-company CSV-research data — per-company changelog");
out.push("");
out.push(
  "Generated by `scripts/csv-changelog.mts`. Documents what each of the 100 CSV-extracted companies gained when the research dataset was wired into `getCompanyBandOverride` + `getCompanyNegotiationContext` as a fallback layer.",
);
out.push("");
out.push(
  "**Resolution order**: curator-authored override (rich `notes`) → CSV-derived fallback → sector-tier default. CSV fallback only fires when the curator hasn't authored a hand-curated cell. This means rich coaching notes (Razorpay, Microsoft, Apple, Adobe, Salesforce, Meta, Amazon) keep their numbers; everything else now resolves to research-grade bands.",
);
out.push("");

const keys = Object.keys(CSV_COMPANY_ROLE_BANDS).sort((a, b) =>
  CSV_COMPANY_ROLE_BANDS[a].companyName.localeCompare(CSV_COMPANY_ROLE_BANDS[b].companyName),
);

let totalAddedCells = 0;
let totalCorrectedCells = 0;
let totalNewOverrideEntries = 0;
let totalNewNegContext = 0;

for (const k of keys) {
  const co = CSV_COMPANY_ROLE_BANDS[k];
  const overrideKey = normalizeKey(co.companyName);
  const ovr = COMPANY_SALARY_OVERRIDES[overrideKey];
  const neg = COMPANY_NEGOTIATION_CONTEXT[overrideKey];

  const missingCells: string[] = [];
  const correctionCells: string[] = [];
  const addedRoles = new Set<string>();
  let csvCellCount = 0;

  for (const role of Object.keys(co.roles)) {
    const roleKey = matchRoleKey(role);
    const ovrRole = ovr?.[roleKey];
    if (ovr && !ovrRole) addedRoles.add(role);
    for (const lvl of Object.keys(co.roles[role]) as CsvLevel[]) {
      const band = co.roles[role][lvl];
      if (!band) continue;
      csvCellCount++;
      const exp = csvLevelToExp(lvl);
      const ovrCell = ovrRole?.[exp];
      if (!ovrCell) {
        missingCells.push(
          `${role} / ${lvl} → CSV adds ₹${band.totalMinLpa}-${band.totalMaxLpa} LPA (median ₹${band.totalMedianLpa})`,
        );
      } else {
        const ovrMid = (ovrCell.totalMin + ovrCell.totalMax) / 2;
        const drift = Math.abs(band.totalMedianLpa - ovrMid) / Math.max(ovrMid, 1);
        if (drift > 0.25) {
          correctionCells.push(
            `${role} / ${lvl}: was ₹${ovrCell.totalMin}-${ovrCell.totalMax} LPA (mid ₹${ovrMid.toFixed(1)}); CSV says median ₹${band.totalMedianLpa} LPA (${(drift * 100).toFixed(0)}% off — flagged but curator-authored entry retained)`,
          );
        }
      }
    }
  }

  if (!ovr) totalNewOverrideEntries++;
  if (!neg) totalNewNegContext++;
  totalAddedCells += missingCells.length;
  totalCorrectedCells += correctionCells.length;

  out.push(`## ${co.companyName}`);
  out.push("");
  out.push(`- **Status before**: ${ovr ? "curator override present" : "no override"}, ${neg ? "neg-context present" : "no neg-context"}.`);
  out.push(`- **CSV coverage**: ${Object.keys(co.roles).length} roles, ${csvCellCount} role×level cells.`);
  if (!ovr) {
    out.push(`- **Added (whole company)**: full salary override entry now synthesized from CSV (was falling back to sector tier default).`);
  }
  if (!neg) {
    out.push(`- **Added (whole company)**: full negotiation-context entry now synthesized from CSV (was empty before).`);
  }
  if (addedRoles.size) {
    out.push(`- **Roles added on top of existing override**: ${Array.from(addedRoles).slice(0, 8).join(", ")}${addedRoles.size > 8 ? `, +${addedRoles.size - 8} more` : ""}.`);
  }
  if (missingCells.length) {
    out.push(`- **Missing info added (${missingCells.length} cells)**:`);
    for (const m of missingCells.slice(0, 12)) out.push(`  - ${m}`);
    if (missingCells.length > 12) out.push(`  - ...and ${missingCells.length - 12} more`);
  }
  if (correctionCells.length) {
    out.push(`- **Wrong info flagged (${correctionCells.length} cells, curator wins)**:`);
    for (const c of correctionCells.slice(0, 8)) out.push(`  - ${c}`);
    if (correctionCells.length > 8) out.push(`  - ...and ${correctionCells.length - 8} more`);
  }
  out.push("");
}

out.unshift("");
out.unshift(
  `> **Aggregate**: ${totalNewOverrideEntries} companies gained full salary overrides; ${totalNewNegContext} gained negotiation-context entries; ${totalAddedCells} role×level cells of missing information added; ${totalCorrectedCells} cells flagged as numerically drifting from CSV (curator entry retained — review backlog).`,
);
out.unshift("");

console.log(out.join("\n"));
