import { t, f } from "./sessionReport/tokens";
import Link from "next/link";

const TERMS_SECTIONS = [
  { title: "1. Acceptance of Terms", body: "By accessing or using HireStepX, you agree to be bound by these Terms of Service. If you do not agree, do not use the platform." },
  { title: "2. Description of Service", body: "HireStepX provides AI-powered mock interview practice, including question generation, speech recognition, performance evaluation, and personalized feedback. The service is intended for educational and professional development purposes only." },
  { title: "3. User Accounts", body: "You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information and to update it as necessary. You must be at least 18 years old to create an account." },
  { title: "4. User Content", body: "You retain ownership of content you upload (resumes, interview responses). By uploading content, you grant us a limited license to process it for the purpose of providing the service. We do not sell your data to third parties." },
  { title: "5. Acceptable Use", body: "You agree not to misuse the service, including attempting to reverse-engineer AI models, scraping content, impersonating others, or using the platform for any unlawful purpose." },
  { title: "6. AI-Generated Content", body: "Interview questions, feedback, and evaluations are generated by AI and are provided for practice purposes only. They do not constitute professional career advice. Results may vary and should not be relied upon as the sole basis for career decisions." },
  { title: "7. Subscription & Billing", body: "Paid features are billed according to the plan selected at checkout. You may cancel at any time. Refunds are handled on a case-by-case basis within 14 days of purchase." },
  { title: "8. Termination", body: "We may suspend or terminate your account if you violate these terms. You may delete your account at any time from Settings, which will remove your personal data from our systems." },
  { title: "9. Limitation of Liability", body: "HireStepX is provided \"as is\" without warranties. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service." },
  { title: "10. Changes to Terms", body: "We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms." },
];

const PRIVACY_SECTIONS = [
  { title: "1. Information We Collect", body: "We collect information you provide directly: name, email, resume text, interview responses, and preferences. We also collect usage data such as session scores and practice frequency." },
  { title: "2. How We Use Your Information", body: "Your data is used to provide and improve the service: generating personalized interview questions, evaluating responses, tracking progress, and delivering features you request." },
  { title: "3. AI Processing", body: "Resume text and interview transcripts are sent to AI language models (Google Gemini) for analysis. This data is processed in real-time and is not stored by the AI provider beyond the request lifecycle." },
  { title: "4. Data Storage", body: "Your data is stored securely using Supabase (PostgreSQL with row-level security). Passwords are hashed. Data at rest is encrypted by the hosting provider. We use HTTPS for all data in transit." },
  { title: "5. Data Sharing", body: "We do not sell, rent, or share your personal data with third parties for marketing purposes. We share data only with service providers necessary to operate the platform (Supabase, Vercel, Google Cloud)." },
  { title: "6. Cookies & Local Storage", body: "We use localStorage to cache session data for offline access and faster loading. We do not use tracking cookies or third-party analytics." },
  { title: "7. Your Rights", body: "You can access, export, or delete your data at any time. Use the Settings page to download your data or delete your account. Upon deletion, your data is permanently removed within 30 days." },
  { title: "8. Data Retention", body: "We retain your data for as long as your account is active. After account deletion, data is purged within 30 days. Anonymous, aggregated analytics may be retained indefinitely." },
  { title: "9. Security", body: "We implement industry-standard security measures including encryption, rate limiting, CORS validation, and content security policies. However, no system is 100% secure." },
  { title: "10. Contact", body: "For privacy concerns or data requests, contact us through the support channels available in the application." },
];

export default function LegalPage({ type }: { type: "terms" | "privacy" }) {
  const isTerms = type === "terms";
  const sections = isTerms ? TERMS_SECTIONS : PRIVACY_SECTIONS;
  const title = isTerms ? "Terms of Service" : "Privacy Policy";

  return (
    <div style={{ minHeight: "100vh", background: t.cream, padding: "60px 24px 80px" }}>
      <div style={{ maxWidth: 640, margin: "0 auto" }}>
        <Link href="/" style={{ fontFamily: f.sans, fontSize: 12, color: t.copper, textDecoration: "none", display: "inline-flex", alignItems: "center", gap: 6, marginBottom: 32 }}>
          <svg aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="15 18 9 12 15 6"/></svg>
          Back to home
        </Link>

        <h1 style={{ fontFamily: f.serif, fontSize: 36, color: t.coal, marginBottom: 8, letterSpacing: "-0.02em" }}>{title}</h1>
        <p style={{ fontFamily: f.sans, fontSize: 13, color: t.inkSoft, marginBottom: 40 }}>Last updated: April 2026</p>

        {sections.map((section, i) => (
          <div key={i} style={{ marginBottom: 28 }}>
            <h2 style={{ fontFamily: f.sans, fontSize: 15, fontWeight: 600, color: t.coal, marginBottom: 8 }}>{section.title}</h2>
            <p style={{ fontFamily: f.sans, fontSize: 13.5, color: t.coal, lineHeight: 1.7, margin: 0 }}>{section.body}</p>
          </div>
        ))}

        <div style={{ marginTop: 40, paddingTop: 24, borderTop: `1px solid ${t.line}`, display: "flex", gap: 20 }}>
          <Link href="/terms" style={{ fontFamily: f.sans, fontSize: 12, color: isTerms ? t.coal : t.inkSoft, textDecoration: "none" }}>Terms of Service</Link>
          <Link href="/privacy" style={{ fontFamily: f.sans, fontSize: 12, color: !isTerms ? t.coal : t.inkSoft, textDecoration: "none" }}>Privacy Policy</Link>
        </div>
      </div>
    </div>
  );
}
