"use client";
import { c, font } from "./tokens";
import Link from "next/link";

const sections = [
  {
    title: "1. Service Description",
    body: `HireStepX is an AI-powered mock interview practice platform. It generates interview questions, listens to your spoken answers, evaluates your responses using AI, and provides scored feedback.

HireStepX is a practice tool only. Sessions on HireStepX are not real job interviews and do not guarantee employment outcomes. Scores and feedback are generated by AI models and should be used as one input among many in your preparation.`,
  },
  {
    title: "2. Eligibility",
    body: "You must be at least 18 years old to create an account and use HireStepX. If you are between 13 and 18, you may use the platform only with the consent and supervision of a parent or legal guardian.",
  },
  {
    title: "3. Account Responsibilities",
    body: `You are responsible for:

- Providing accurate information when creating your account.
- Keeping your login credentials secure and confidential.
- All activity that occurs under your account.
- Notifying us immediately if you suspect unauthorized access to your account.

We reserve the right to suspend accounts that appear to be compromised or are being used in violation of these terms.`,
  },
  {
    title: "4. Free Tier and Paid Plans",
    body: `HireStepX offers a free tier that includes 2 AI mock interview sessions. Beyond the free tier, you can purchase:

- Session packs: A fixed number of additional interview sessions.
- Subscription plans: Monthly or annual plans with a set number of sessions per billing period and additional features.

Plan details, pricing, and session limits are displayed on the pricing page and may be updated from time to time.`,
  },
  {
    title: "5. Payment Terms",
    body: `All payments are processed through Razorpay and are charged in Indian Rupees (INR).

- Subscriptions renew automatically at the end of each billing period unless cancelled.
- You will be charged at the beginning of each billing cycle.
- Prices are inclusive of applicable taxes unless stated otherwise.
- You are responsible for ensuring your payment method is valid and has sufficient funds.`,
  },
  {
    title: "6. Cancellation and Refunds",
    body: `You may cancel your subscription at any time from the Settings page. Upon cancellation, you retain access to paid features until the end of your current billing period.

For our detailed refund policy, including conditions for session pack refunds and subscription refunds, please see our Refund Policy.`,
    hasRefundLink: true,
  },
  {
    title: "7. Acceptable Use",
    body: `You agree not to:

- Upload abusive, offensive, or illegal content during interview sessions.
- Attempt to reverse-engineer, decompile, or extract the AI models or algorithms used by the platform.
- Scrape, crawl, or automatically extract data from the platform.
- Use the service to impersonate another person or entity.
- Interfere with or disrupt the platform's infrastructure or other users' access.
- Share your account credentials with others or allow multiple people to use a single account.
- Use the platform for any purpose that violates applicable laws.`,
  },
  {
    title: "8. AI Disclaimer",
    body: `AI-generated interview questions, evaluations, scores, and feedback are provided for practice and self-improvement purposes only. They do not constitute professional career advice, coaching certification, or employment guarantees.

AI outputs may occasionally be inaccurate, incomplete, or inconsistent. You should not rely on AI feedback as the sole basis for career decisions. We recommend supplementing AI practice with human mentorship and professional career guidance.`,
  },
  {
    title: "9. Intellectual Property",
    body: `- Platform: HireStepX, its design, code, branding, and AI systems are owned by HireStepX. You may not copy, modify, or distribute any part of the platform without written permission.
- Your content: You retain full ownership of content you provide, including resume text, interview responses, and personal information. By using the service, you grant us a limited, non-exclusive license to process your content solely for the purpose of delivering the service.
- We do not claim ownership of your interview responses or resume data.`,
  },
  {
    title: "10. Limitation of Liability",
    body: `HireStepX is provided "as is" and "as available" without warranties of any kind, either express or implied.

To the maximum extent permitted by law, HireStepX shall not be liable for:

- Any indirect, incidental, special, consequential, or punitive damages.
- Loss of profits, data, or business opportunities arising from your use of the service.
- Any inaccuracies in AI-generated content.
- Service interruptions, downtime, or data loss.

Our total liability for any claim related to the service shall not exceed the amount you paid us in the 12 months preceding the claim.`,
  },
  {
    title: "11. Termination",
    body: `We may suspend or terminate your account if you:

- Violate these Terms of Service.
- Engage in fraudulent or abusive behavior.
- Fail to pay for purchased services.

You may delete your account at any time from the Settings page. Upon deletion, your personal data will be permanently removed in accordance with our Privacy Policy.`,
  },
  {
    title: "12. Changes to These Terms",
    body: "We may update these Terms of Service from time to time. When we make material changes, we will update the \"Last updated\" date at the top of this page. Continued use of the service after changes constitutes acceptance of the updated terms.",
  },
  {
    title: "13. Governing Law",
    body: "These terms are governed by and construed in accordance with the laws of India. Any disputes arising from these terms or your use of the service shall be subject to the exclusive jurisdiction of courts in India.",
  },
  {
    title: "14. Contact",
    body: "For questions about these terms, contact us at hello@hirestepx.com.",
  },
];

export default function TermsOfService() {
  return (
    <div style={{ minHeight: "100vh", background: c.obsidian, padding: "60px 24px 80px" }}>
      <div style={{ maxWidth: 720, margin: "0 auto" }}>
        <Link
          href="/"
          style={{
            fontFamily: font.ui, fontSize: 12, color: c.gilt, textDecoration: "none",
            display: "inline-flex", alignItems: "center", gap: 6, marginBottom: 32,
          }}
        >
          <svg aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="15 18 9 12 15 6" /></svg>
          Back to home
        </Link>

        <h1 style={{ fontFamily: font.display, fontSize: 36, color: c.ivory, marginBottom: 8, letterSpacing: "-0.02em" }}>
          Terms of Service
        </h1>
        <p style={{ fontFamily: font.ui, fontSize: 13, color: c.stone, marginBottom: 48 }}>
          Last updated: April 2026
        </p>

        <p style={{ fontFamily: font.ui, fontSize: 14, color: c.chalk, lineHeight: 1.7, marginBottom: 36 }}>
          These Terms of Service ("Terms") govern your use of HireStepX. By creating an account or using the platform, you agree to these terms.
        </p>

        {sections.map((section, i) => (
          <div key={i} style={{ marginBottom: 32 }}>
            <h2 style={{ fontFamily: font.ui, fontSize: 16, fontWeight: 600, color: c.ivory, marginBottom: 10 }}>
              {section.title}
            </h2>
            <p style={{ fontFamily: font.ui, fontSize: 14, color: c.chalk, lineHeight: 1.8, margin: 0, whiteSpace: "pre-line" }}>
              {section.body}
            </p>
            {section.hasRefundLink && (
              <Link
          href="/refund"
                style={{
                  fontFamily: font.ui, fontSize: 14, color: c.gilt, textDecoration: "none",
                  display: "inline-block", marginTop: 8,
                }}
              >
                View Refund Policy →
              </Link>
            )}
          </div>
        ))}

        <div style={{ marginTop: 48, paddingTop: 24, borderTop: `1px solid ${c.border}`, display: "flex", gap: 20 }}>
          <Link href="/terms" style={{ fontFamily: font.ui, fontSize: 12, color: c.ivory, textDecoration: "none" }}>Terms of Service</Link>
          <Link href="/privacy" style={{ fontFamily: font.ui, fontSize: 12, color: c.stone, textDecoration: "none" }}>Privacy Policy</Link>
          <Link href="/refund" style={{ fontFamily: font.ui, fontSize: 12, color: c.stone, textDecoration: "none" }}>Refund Policy</Link>
        </div>
      </div>
    </div>
  );
}
